package Util;
import java.util.Arrays;
import java.util.List;

public class A2_Texts {
    public List get_texts(){
        return texts;
    }

    private List<String> texts= Arrays.asList("I don't blame the developers on this one. We trust whatever Digital Foundry " +
            "says, in this case they were objectively wrong, which compromises their technical analysis credibility",
            "The comment on how using the DMCA as an option over a legal action is totally inappropriate. The " +
                    "copyrighted parts of the review are used with fair-use and are protected speech. What you " +
                    "mentioned is the same as saying asset-flip devs that DMCA a review that calls them out is doing " +
                    "the right thing. To put it simply you are advocating a dangerous president.","I don't get " +
                    "it. This seems pretty clean cut. I kept waiting for an \"but wait, there's more!\" And it just " +
                    "never came. DF made a serious mistake, got called out, and apologized. What's special " +
                    "here?","Why are you guys painting the developers as the bad guys in that intro and " +
                    "description? The CEO could have been more calm and respectful, but he's still justified in being displeased about what Digital Foundry did. What Digital Foundry did was an accident but accidents should still be called out.","I feel like this game was inspired by star wars pod racing and then took it to the next level and made the idea of high speed racing in a hover vehicle with spot section decisions more amazing.","The update is weaker than the studios response. It's not solid 60 fps and that's inexcusable. The developer didn't have the patch Available on time, we as gamers should sue the publisher for releasing an unplayable mess. I got this at launch played twice and not since even though I have xbox one x it's too little too late.","To the writers, Brian and Eddy: Goodness, you guys do a great job of hooking sympathy to those certain groups, then explaining how their view could be wrong in the friendliest way possible. Congrats on the writing.","Oh yeah the teacher is a total, incompetent piece of shit. Why couldn't the teacher just take the extra effort to write out his notes on the blackboard and ask Shouko to confirm when she was ready to move on? And he has the audacity to judge Ishida for seeing Shouko as a burden when it was his fault that she was seen as one.","Wow. I think that tryin to explain why I find this video so great would only end up banalazing it.\n" +
                    "So I'll just thank you for making it. I loved it.","I'm completely deaf in my right ear and I " +
                    "was so completely mortified with Shoko's treatment that I was sobbing and couldn't get past the " +
                    "first half hour. I related so much to her struggles and to see people treat her like garbage was" +
                    " just the worst feeling.","I feel like the Movie was way better when you explained those " +
                    "suicides in Japan, because there's a cultural disconnect between the western audience and the " +
                    "japanese ones. I felt it was over-the-top or unrealistically cruel when I first watched it. I " +
                    "then realized Japanese high School isn't like American high school. This sucks because the movie doesn't explain that to you because it's meant for a Japanese audience.","I feel like the Movie was way better when you explained those suicides in Japan, because there's a cultural disconnect between the western audience and the japanese ones. I felt it was over-the-top or unrealistically cruel when I first watched it. I then realized Japanese high School isn't like American high school. This sucks because the movie doesn't explain that to you because it's meant for a Japanese audience.","Great mind-opening video, your video sums up of school life and human interaction. That hesitation because afraid of expressing emotions as they can be used against you. However as long as you can find a person who can connect with you, because you are never not alone.","People, especially men, aren't told to avoid emotional reaction or expressing them, but rather to control those reactions to a suitable expression at a suitable time. There is a world of difference between those two, and only those confused about the difference really have the emotional issues that come from actually avoiding emotions and try to put those emotions away. It is a self-inflicted issue stemming from misinterpretation or self-delusion, not outside pressures.","I call this the painting problem. Painting the walls of a room seems easy to an amateur: You just buy a few gallons at Home Depot and slap it on. But a professional knows that prep, trim, and cleanup are 80% of the job and they take skill. Anybody can slap paint onto the middle of a wall. What's difficult and time-consuming are making the edges sharp and keeping paint off the damn carpet.","My experience is a careful amateur painter is 1000% better than an average professional. Professionals are certainly a lot faster, but if you look carefully at their work it is in the main very shoddy.\n" +
                    "If you want a good result don’t skimp on the tools. Buy good quality brushes, rollers, filler, " +
                    "throws and paint. Also buy an edger to cut in the walls and ceilings. One final tip buy some of the disposable plastic liners for the roller tray so you don’t have to spend time washing out the tray at the end of the day.","Not sure where you're from but in Germany there are industry standards professionals have to adhere to. Sure, there are sloppy professionals like in any other job too but if they adhere to the industry standards, the result will be pretty much what you expect and they're not allowed to take shortcuts that result in lower quality work.\n" +
                    "On the other hand, coming from a country that takes its trades extremely serious, I was shocked " +
                    "about what I observed every time I visited the UK. It seems the expectations vary drastically between different countries (though I'm sure there are quality professionals in the UK too).","Yes I agree especially the cleaning part. The kitchen and the rooms close to the kitchen it is critical to clean and clean and clean. The prep should take longer than the painting.\n" +
                    "On the sand paper front make sure to spend money there. Cheap sandpaper last 2 nanoseconds and " +
                    "does a terrible job.","It is frightening to see bikeshedding in practice. I used to work for a " +
                    "regional transportation authority that would administer hundreds of millions of dollars in federal/state/local road projects. Local leaders would monthly come in and sit at a huge round table (40-50 cities/counties/regional leaders) and vote on projects. 800 million dollar projects would sail through with almost no questions in the first five minutes, but then the leaders would spend the next two hours of the meeting debating about the $100,000 pilot project to help the homeless.","Aside from the \"sample size of one\"-issue: how much time did your parents take, and how much effort and preparation time, and how did that compare to the time and effort the professional needed? It could be a trade-off issue there.\n" +
                    "Also, note that this thread started with a comment about how many developers don't appreciate " +
                    "what the actual hard problems in their own line of work are, and how that produces poor results because of that. I expect that to be true of any profession that doesn't have some kind of rigorously enforced standard.","I really think microservices are a process win not a technical win. It's easier and better to have 5 teams of 10 managing 5 services. Then having one team of 50 managing a one super service.\n" +
                    "When I see a team of 7 deciding to go with microservices for a new project I know they're gonna " +
                    "be in for a world of unnecessary pain.","I am a victim of this, Because of the competitive " +
                    "nature of things in my part of the world, I had to skip the extra curricular activities and dedicate all my free time (4-5 hrs a day) for studies and I am completely out of balance now. It's very difficult for me to find a balance or enjoy the activities now.","Critical thinking is universal though. It's not a necessity to have a solid judgment of a piece. \"Critical abstention\" is a possibility, and primarily formal analysis is another (eg. search for common communication red flags).\n" +
                    "I don't think that the parent idea of removing likes and counts is realistic (in any imaginary " +
                    "scenario I can think of).","They will never do it because it’s those little numbers that give you your dopamine fix, and thus central to their revenue.\n" +
                    "Social media is a game and the score is whatever metric is shown. You want to most points for " +
                    "yourself and you only want to participate in popular content in the hopes it will earn you more " +
                    "points.","Considering a lot of the art collectors buy is immediately whisked away to " +
                    "temperature-controlled, pitch dark warehouses where it can be kept safely until it's put back on the market a decade later, I really wouldn't expect the value to be related to what the art looks like at all.","Art is also extensively used for purposes of, ahem, conveniently moving large sums of money around. It would be difficult to differentiate an unusual price due to money laundering motives from an unusual price due to manipulation.","My wife works in the high-end art and auction world.\n" +
                    "I always joke that artists are the most extreme capitalist you will ever find. This is a world where a dinner table can easily be sold for 1$mio because it's owned by some famous person. Pretty fascinating world.\n" +
                    "On a slightly different note. This is also the reason why I think cryptocurrencies/tokens are " +
                    "going to be doing just fine. Humans very rarely exchange and value based on utilitarianism alone" +
                    ".","Manipulation is the game they're playing, that is the whole market. Fuzz your eyes to abstract the details of the art pieces and only look at the social structure around it, and that's all the information you need to predict demand.","I found this contradictory. Galleries set prices, but \"desirable collectors are well educated consumers and won’t blatantly overpay.\"\n" +
                    "What are collectors educated in, exactly? Is it reading the collective market and understanding the pricing signals it generates? Is it marking new art to this market?\n" +
                    "If the latter, how does that work if the art has no intrinsic value?","I suppose this means formal or accidental training in art and shared taste with the art market community. I presume the minimal level of skill is identifying famous artists' work from similar pieces of not-so-famous artists, recognizing influences and obvious pastiches, and so on.\n" +
                    "I.e. someone who had credibility among the art crowd and whos purchase of a work will function " +
                    "as social proof of the gallerists' brand.","Aesthetically pleasing, possibly depending on what you mean; that description sounds like it would cover a lot of metal album covers.\n" +
                    "But relaxing? That would .. require more explanation.","Art is not utilitarian. Art doesn't have the function of being hanged in a wall or maximise good feelings. That's just a low trick to make common people buy it.\n" +
                    "Art is (self) expression.","It feels weird to say there's no conflict in Eurogames.\n" +
                    "Power Grid is pretty relentless and brutal - there's no violent aspect to it, but you can mess your opponents pretty badly, and it still hurts.\n" +
                    "The only time I've managed to get my girlfriend to swear at me was when I stole the line she was" +
                    " clearly trying to build in Ticket to Ride.","If they cry that means that they are invested and " +
                    "you are doing something they care about. I can't think of a better way to learn about how emotions can control you than surrounded by family in a safe environment where nothing truly important is on the line. You are doing grade A parenting right there.","I believe dealing with your emotions (especially frustration in the case of losing) is one of the big teachings of board games.\n" +
                    "At least, this believe is my only reason for playing certain games with my kids like " +
                    "Snakes-and-Ladders. I fail to recognize them as actual games because there are practically no decisions to be made. With most games, I can let my kids win by making stupid decisions. With Snakes there is no such option. The dice can force me to win and my kids have to deal with losing.","We regularly invite some friends for a \"game evening\" not \"just because\". Have dinner together, bring the small kids to bed, then have a round of Dominion, Alhambra, whatever.\n" +
                    "That does not work for long games like Axis & Allies, because you would need a whole day, though" +
                    ". Fortunately, there are plenty of shorter games as well.","My kid is 3 and loves Monopoly " +
                    "Junior. Every time anyone lands on one of her properties, she launches in to this apologetic refrain about how next time you can stay for free. She's gonna be a handful as a teenager.","It was created to teach about the downside of capitalism. I don't see what's so terrible about that. Capitalism isn't perfect nor the Devil.\n" +
                    "When people don't actually play by the rules it turns into a mess.","I played Catan about 1000 times in 1997, and it did nothing to hurt my friendships. If your friendship can't survive this game, I wonder if there's any game it can survive. Well, there are friendlier games, but Catan is fairly middle of the road in how much you can screw someone over.\n" +
                    "The only true dick move in the game is to trade away all of a certain good in lucrative trades, " +
                    "and then take it all back with a monopoly card. Most people have enough decency not to do that. " +
                    "Then again, at my house, we play it in a fairly friendly way and don't try to cripple each other" +
                    " unless we have to.","Can confirm that a game of Diplomacy will take a group of happy friends " +
                    "and turn them into scheming backstabbers who will never trust one another ever again for the " +
                    "rest of their lives.","The solution is to only play Diplomacy with a group where everyone is a " +
                    "known scheming backstabber who will never trust one another ever again for the rest of their lives! Have tried, can confirm it works. Good times.","I am probably the only one playing Britain in the history of the game who never made it off the damn island. The game is really hard."+"I know it's not the main thrust of the article but to note: monopoly is supposed to end with one winner by a landslide because it was created as a critique of capitalism without land value tax. The original game had two sets of rules, one that was sustainable and one based on the current insanity you can find outside your window.","I don't think that's the problem! It's (as noted in many online articles) the last 2/3 of every game is the richest person getting more and more so, until too long later they win. Kind of a drag for everyone else.","I like it. I personally don't have an affinity with the colours. Red for amazing? Red, to my mind is danger, and I would naturally associate that with bad things. I think green for an amazing day.\n" +
                    "Also I'd find it easier to read if it were rotated 180 degrees and the months were stacked " +
                    "horizontally.","I think it would be easier to see some effects if you would change the layout to one row per week or 14 days per row. That way seasonal effects like a November depression would be much clearer.\n" +
                    "The current layout would be a good choice to display the financial situation, as the cash level tends to change on a monthly basis for many people.\n" +
                    "Nevertheless, nice tool.","I just want to commend you for very clean code. It is a pleasure to " +
                    "look at something written this clean, even if it is a smaller app.","Dang, I was planning on " +
                    "writing nearly this exact app as a side project. In any case I've set a daily calendar reminder " +
                    "to update it, thanks!","I think it’s great. I’d love to see somethin similar for chronic diseaseas. When you see a doctor once per several months, it’s impossible to really tell him if you are doing better or worse due to recency bias. I’d love to monitor pain in my joints on a daily basis and have a real data points to show.","This is easily blamed on the shutdown, but it isn't that simple: Falcon Heavy static fire has been postponed numerous times. On Tuesday (Jan 16th), it was cancelled once again, but with no new target test date. That indicates that SpaceX is still working on the rocket/pad.\n" +
                    "I didn't find information on when they'd be ready again, but blaming a delay on Falcon Heavy's " +
                    "static fire test on the Government Shutdown is only half the truth.","SpaceX had activities " +
                    "planned for Sunday and Monday which have been canceled. New rockets and new launch pads (2/3 of the booster fueling equipment is new) are always like this; the first shuttle flight sat on the pad from December through April. It's very tedious for the range people because both fueling the rocket (wet dress rehearsal) and fueling and static firing it are dangerous events that require exclusion zones.","I can strangely relate to this comment, to a higher level than I can usually 'relate' to other comments about workflow or thought processes.\n" +
                    "Regarding procrastination, the advice on tying small tasks together is bang on. One task leading" +
                    " to another usually results in a more productive day, I've found. The pessimist in me wants me " +
                    "to credit/blame this to the games I've played as kid, where the level up/task done dopamine boost is enough to get through the next level/task.","They did go through with a Wet Dress Rehearsal on Saturday, though, which already validates many things just prior to engine ignition. So if they were confident to continue with a static fire on Monday and there were no other issues known I'd say it's fair to blame it on the shutdown. Of course, more issues could arise during the test, but we won't know now.","Officially yes, but I can imagine there being some bureaucratic delay until it's in full effect/everybody got the news. Not a lot of time between midnight Friday and Saturday.\n" +
                    "In German radio news, the US correspondent explained that the weekend should still be fine, with" +
                    " full effects of the shutdown beginning around Monday with the new week.","They knew that, for " +
                    "certain, only after Friday midnight. It's not that far-fetched to assume that most people working that Saturday would already be asleep during that time and just showed up at their work on Saturday like it's business as usual.","So, is SpaceX now eligible for contract-breach money from the government for this delay? I assume SpaceX 'rents' the facility at KSP from the government. If that facility shuts down, then the government isn't upholding their part of the deal with SpaceX.\n" +
                    "Say, as a company I had a deal where I rent an office, and the owner of the office decides for " +
                    "2+ days I have no access to my office, because one-sided reasons, I can claim lost revenue from the owner, right?","At their current rate of launches it probably just doesn't make any sense to put a lot of resources into it.\n" +
                    "There has been upgrades in automation for the ranges last year which allow a higher frequency of launches. Plus they started launching again from their second Cape Canaveral pad.\n" +
                    "I read that even with their own facility they would still be affected by a shutdown.","I would " +
                    "imagine the launch requires the participation of civil servants from NASA who I assume all the " +
                    "range safety people work for and I assume they use the coast guard to keep boats away from the " +
                    "danger zone two.","I don't think anyone's opinion on whether it's reasonable or not really matters for this article. The fact is that they have no budget from which to pay people who operate all the things at the space centre, so they aren't working. I don't think it's any more complicated than that is it? What more could they say.","Watched the video on the page demoing the falcon heavy concept. The real pictures don’t have the water tower at the launch site like the concept video. Is there some reason the water tower was in the demo design but not the real thing ... — maybe the water tower is mobile and only in place during an actual launch? Or is this closer to a case where somebody thought the water tower would look cool so they put it in the demo video ...?","This is the thing that blew my mind last time:\n" +
                    "The shoreline of San Francisco is a national park (donated when the military base here closed). There's a restaurant on the shore called Cliff House, whose landlord is the US government.\n" +
                    "During the shutdown, the government forced the restaurant, a private establishment, to close. " +
                    "The owners and the kitchen staff were not allowed to make a living. And because they aren't government employees, they don't get any restitution when the government is funded again.","I think the main idea is that you can do little quick easy things that can have a big impact in the long run.\n" +
                    "On the way to your next class think about the lesson is there anything you've learned that you didn't know? In what ways can you restate the lesson, what are the main ideas. What possible questions could be asked.\n" +
                    "During lunch read the summary section and see if you can connect any dots.\n" +
                    "Looking at the homework early (without even solving them) will give you ideas to ponder and " +
                    "questions to ask during lecture.","Hello,\n" +
                    "I am from London. There are much reasons why I would like to join to your internet forum. Firstly, for example I’ve seen few good download links for movies, music, softwares and others. Secondly I like that everything what I need is at one forum. You know, I am studying high school of telecommunication and everything about computers is my hobby too.\n" +
                    "I want ask how many members can be in this internet forum?\n" +
                    "Thanks for your answer.\n","I have many time at weekends so I am helping my mom with much houseworks. \n" +
                    "Firstly we are going to nearby supermarket for some vegetable and fresh meat. After the shopping at home I am making a tasty lunch. After lunch in the afternoons I am helping at garden. Every time I am washing our dirty car and my mom is taking care about flowers. After that I am cleaning the tile floor in house and my mom is going to the laundry with some dirty clothes.\n" +
                    "In the evening everything is perfect. So we are very happy. \n","Hi Sara,\n" +
                    "I am writing you a quick email because I will miss the English lesson Friday. It is my boyfriend’s birthday, and I have booked a table at a great restaurant. \n" +
                    "I would like to ask your help. The teacher always gives us a lot of handouts. Could you ask for a copy for me. I will try to do all the work at the weekend.\n" +
                    "Can I come to your flat on Saturday morning for a coffee and to pick up the handouts - and to have a chat. \n" +
                    "Lots of love, \n" +
                    "Bridget\n","Hi Rikardo, \n" +
                    "What a shame. You missed my birthday party. I know you had a good reason: you were working on the other side of the country and couldn’t travel home for it. \n" +
                    "Anyway, we had a great time. We all met up for a drink at the Golden Eagle and then went on to Mazzi’s that new restaurant in the centre of town. After that we moved on to a bar.\n" +
                    "When are you coming home? We should meet up soon. \n" +
                    "Love, \n" +
                    "Lorna\n","I bounced on my boys soda can to this. Be sure to bounce on it before you slice it up. Aluminum is sharp and your cornhole is sensitive. \n" +
                    "That’s what my dad always said to me when he would leave to go steal peoples lawn furniture and " +
                    "sell it on eBay to buy me CDs and gummy bears.","This doesn't seem to have the Slenderman I've " +
                    "come to expect. I don't feel the mystery, or the raw terror that his character is supposed to " +
                    "inspire from this trailer which amounted to a bunch of random scenes without any seeming connection between them. Terrible trailer.","The film centers on Thor, reeling after an embarrassing defeat at the hands of Hela, who lands on a distant planet and is immediately kidnapped and forced into gladiatorial combat. His opponent: The Incredible Hulk, last seen leaving Earth at the end of Avengers: Age of Ultron.");
}
