package Util;
import java.util.Arrays;
import java.util.List;

public class B1_Texts {
    public List get_texts(){
        return texts;
    }

    private List<String> texts= Arrays.asList("34BigThings never once promised that the game would 4K on high settings, they " +
            "only expected the game to run that way. I'm glad the analysis will change because the patch that allowed the Xbone X went live almost a month prior. What I hate the most is how I've heard some people call the developers lazy. Being apart of their Discord for months now and been playing the game for a year before console launch I have to say, these developers are NOT lazy. The work put into the game is amazing, from the world design, the crafts, levels, music, and patches come out regularly. 34BigThings does not deserve to be called lazy because Redout is a game that does many things right like no microtransactions and it has a delivering gameplay. I highly recommend it to anyone.","For sure this is giving them a lot of free PR.. Threateninglegal action is bullshit though, and it would take a lot for my to buy a game from such an asshat developer.. They could just have reached out to DF in a civil manner. DF are not responsible for the actions of fanboys, they were nothing but respectful in their video, basically saying that the game \"fell short of their expectations\"\n" +
            "DF has gone back to titles several times to update their results after talking to the developer, " +
            "patches, or more info coming in.","Correct me if I'm wrong, but isn't the phrase pertaining to " +
            "conformity, \"the nail that sticks out gets hammered down\"? You could tell from that Shouko being " +
            "bullied was gradual, from some of the kids being more into it than others, but ultimately going along with it so they themselves don't end up as outcasts. Along with the bullying issue Japan has I've also heard of other problems such as stalking cases, so the suicide stats didn't surprise me.","Thank you for sharing your experience and views, I was nearly brought to tears. My own ongoing journey of learning to overcome ingrained repression brings am empathy to your points, and your encouragement is one of the most important messages to share to help people experience life in a more emotionally fulfilling way. Keep up the great work - Your new subscriber.","The leading cause of death for teenagers is suicide everywhere. Its not exactly unique to japan. This is mostly a cause of teenagers being dumb, self absorbed egotistical hormon driven beings. These attributes creat both the bullies and the victims. Both of these come from emotional insecurity and social inexperience. I should know, I have been both, not that long ago. And as such I can say with honesty that the solution can not be on a societal level. Human biology and society makes thesw issues unavoidable. What can solve it is personal fortitude of those affected.\n" +
            "It is psychologists we need not public awareness campaigns.","That may be a bad analogy, considering painting your own apartment is something a great deal of people do, and often with good success.\n" +
            "My parents (not in any way experts on that field) painted their entire house themselves, except for two " +
            "rooms that were painted by a professional painter, and the professional painter left much worse corners than my parents. This was the paid-for result (ignore the dark corner at the bottom, that’s caused by the flash).","I agree strongly with your first point, for the simple reason of “unknown unknowns.” Maximizing the optimization of your current situation, so to speak, can often result in missing out on opportunities which would bring you to a higher, better level than the one you are on currently.\n" +
            "Extreme focus and hours can be effective in short bursts, but need to be balanced with some time for " +
            "randomness, wandering, and other non-planned activities. One should always be trying to expand their current intellectual domain, but it’s nigh impossible to do so if you keep your head down 24/7.","This is the opposite of what they should have done. Shows just how much of an echo-chamber Facebook has become. This is just adding another metric by which garbage can be made legitimate and vice versa.\n" +
            "Facebook would be a much better platform if they removed the like and comment count from every post. It’s those numbers that lead people to believe that garbage is legitimate in the first place. By hiding these numbers it would force people to think for themselves.\n" +
            "Same thing with YouTube. Fake News becomes real news when it had enough views, likes, upvotes, comments," +
            " etc.. These counts don’t really need to be shown to the end user.","If you really want to fight the root of the problem, it's not likes and comments, but education.\n" +
            "Should we censor social media, because people are too stupid to deal with it? I don't think so and if you do, you're playing in the hands of corporations who want a cheap work force.\n" +
            "Your \"solution\" isn't a solution, but a hot fix that will cause more damage in the future. It's " +
            "exactly the shortsighted crap politics are trying to do right now to get immediate results.","The experience from a few months ago during a conference showed me that education won't fix echo chambers.\n" +
            "It was a conference that was organized by a organization that holds one of the major initiative against false news, and where one of the main tracks was about addressing the issue of false news. Last year they had a massive booth at the middle of the conference hall about false news. This year they brought in a key note speaker which brought several political slides while making misleading conclusions that was later proven to be false, but the whole thing echoed with the audience. It seemed to not matter a bit that it also just happened to be false.\n" +
            "When facts get in the way of a political message, even the most educated seems to let the facts go if " +
            "its align with their own views. I wish education would work, but I don't see it as a proven method to " +
            "solve echo chambers or political news.","I agree, but it's impossible to educate everyone on any subject. I think in this case, people who are experts in the matter, should give a reputation rating on the article. That would be really great. For example, I am no expert in theoretical physics, but I may enjoy an article about it, but how do I know it's not a bunch of bullshit I am reading? If I see that Stephen Hawking gave it a 5 star reputable source rating, I \"know\" I can believe it.","People everywhere are going away from this model as \"experts\" are consistently bribed through various means.\n" +
            "There is no good short-term fix. People need to become more educated and adapt. If the argument is that " +
            "they can't, well, maybe our brains have been defeated entirely by advertising and messaging. It wouldn't be the first time a complex problem was mostly solved.","Art is not utilitarian. Art doesn't have the function of being hanged in a wall or maximise good feelings Except when it is, especially in architecture, product design, and some clothing. Sometimes it is just there to distract you from something crappy, sometimes it is there to make folks happier.\n" +
            "That's just a low trick to make common people buy it. Only, it isn't always. A lot of common people are buying stuff to make their home prettier - not everyone will hang disturbing pictures on the wall because folks would rather stare at something less disturbing on a daily basis. Some is positive, some makes a statement, and so on.\n" +
            "Art is (self) expression. Except when it isn't. I can't imagine every animator at disney (back when a " +
            "lot was watercolor) was expressing themselves, just like a lot of commissions aren't self-expression. " +
            "Some folks just do things they think will sell or others will like. Sometimes it is just something the person thinks looks neat (no more expressive than a webpage layout or product design, honestly).","The sentiment can be appreciated, but as a general statement I believe this is false. As an example: when new hotels are built, they are commonly outfitted with a collection of original art consisting of pictures and sculptures. This is certainly done to a large degree due to the utility of the art, which serves to make the hotel more interesting and aesthetically pleasing. Would you argue that decoration for such a purpose does not constitute art?","For me, it's always a challenge to play board games with my kids.\n" +
            "They are now 8, 6 and 4, and none of them wants to lose. It always ends up with someone crying, sometimes with all of them crying (including the winner).\n" +
            "For other parents who have the same issue: I was able to \"fix\" this situation by declaring the winner as the person who is able to take defeat without crying. After that I mostly can declare all of them winners. Sometimes I'm able to end the game nicely like that.\n" +
            "Just saying that playing a board game with small kids is not always as easy as your imagine it to be.","Kids are always playing the \"game\".\n" +
            "In this case, they won't get anything out of crying, so I guess it is purely out of frustration.\n" +
            "A lot of times, the winner also enjoys rubbing it in, and making the others cry. Kids have all the survival emotions, and none of the social skills to hold back on them. But that's probably our job as a parent, to teach them the social skills.\n" +
            "Better they learn it now, that when that colleague got that manager job they thought they were entitled " +
            "to.","Seconding this. My boys love their tablets and their Xbox, which I play with them and don't " +
            "discourage (video games have their positives), but our real quality time is playing board games. It's wonderful to watch my four and six-year-old \"get it\" while interacting with them on a personal level. Earlier this year I discovered thrift stores are a wealth of games and I'll bring home a stack of new ones to try out every couple of weeks for less than $20. We try them out and it's like trying out novel ways of thinking much of the time. I highly recommend this as a way of connecting to your kids.","I know Phil Eklund primarily from hard-core science simulations such as High Frontier and Biosgenesis. I do know him, but I wouldn't rank him among game design superstars such as Uwe Rosenberg or Reiner Knizia. His games are not exactly mainstream.\n" +
            "Speaking of which, this article suggests that boardgames are niche, but games like Siedler von Catan, " +
            "Agricola, or the many, many games by Reiner Knizia, are absolutely mainstream. At least in Europe. I spent 1997 giving everybody Siedler von Catan for their birthday (and later the Dutch translation), so I would hope everybody vaguely interested in boardgames has it by now.","It teaches that property breeds property, and by the laws of compound interest, whoever gets a big lead first usually wins.\n" +
            "Everyone who's played Monopoly more than a few times quickly understands that:\n" +
            "If it's early and you have an opportunity to acquire property, you take it\n" +
            "If you are out of cash and land on an unbought property, it's usually best to mortgage your other properties. This teaches the lesson of how leverage and debt, judiciously used, is to the capitalists's advantage.\n" +
            "If it's getting later in the game, usually nobody should willingly grant someone else a monopoly unless " +
            "they themselves get one in return.","Even with board full of experienced players, every nation can have a bad start every once in a while. Sometimes people do gang up on you at the start.\n" +
            "However, if you play lots of games, and never get off the British Isles, you might want to look for a different hobby.\n" +
            "The game is meant to be hard: after all at most one in seven people can win. (Unless you are a " +
            "drawmonger and consider that an acceptable outcome).","At least with Dominion, I'd say that predicting when the game is ending and adjusting your play is an important part of the game.\n" +
            "And unless it's really one-sided (which sucks, and maybe there is an argument that Dominion lends itself" +
            " to develop one-sided games without recovery) or whoever you are playing against is keeping mental count of everyone's point (which wouldn't be impossible, but I've never met someone actually bothering to do it) they won't be able to say \"I won\" before everyone has counted out their points.","Hi HN, author here.\n" +
            "This is small tool I made during Friday and Saturday. The idea for this tool is not new at all, but I've never seen this format online before.\n" +
            "The tool is based on an image I found on the internet and was coded using a Node.js server with basic jQuery for the frontend on the Glitch platform.\n" +
            "Hope you like it!","Great idea for a personal tool! Two things:\n" +
            "The way this is organized isn't great for visualization. We read left to right, but since days are laid out vertically this means that horizontally adjacent cells are actually a month apart. A standard calendar interface would be more appropriate for seeing how your mood changed day-to-day (and be less confusing to interact with).\n" +
            "Also noticing that the line graph is deceptive; it only interpolates one point for each month, by " +
            "averaging the entire month together. That's more of a bar graph.","This is nice, I would like to see an output of that, but there's no way I'd be doing this daily through a web page. Something like a notification each day on a smart watch (which I don't have) would work. Even phone would be a bit much I think.\n" +
            "Which brings me to - definitely show the input before output on the phone. The output is a huge empty " +
            "grid for most new users, even for returning users it might not show anything recent, input is something user would want to interact with ASAP when using this service.","I can imagine something like this being useful in psychotherapy. Your phone could ping you to answer once-per-day, allowing you to optionally enter comments.\n" +
            "American Clinical Psychology and Psychiatry are strangely devoid of routine outcome measurement. This " +
            "would be a step in the right direction. Similar Likert-type scales could also be useful for people who struggle with intrusive thoughts or hallucinations.","I've been using that app too, but I haven't found the data particularly interesting or meaningful.\n" +
            "The other thing I've also been doing that I've found much more fulfilling is writing down a daily highlight at the end of each day. I just add an event to a dedicated calendar that summaries the best moment of my day.\n" +
            "It's been really interesting to look back over, and it's a great memory prompt, because it gives me a " +
            "way of looking back at the enjoyable times throughout the year. I've been going for just over a year, and I really don't see any reason to ever stop!","I used to do the same but in analog way when I moved to the Netherlands. The weather there affected so much my mood that I started to keep track of it together with the daily color of the sky.\n" +
            "I kept a big paper sheet next to my bed with a bunch of pencils. The problem I realized later on is that mood changes quite a lot during the day, so just checking once a day might not be very representative.\n" +
            "I had \"the diary\" for 4 or 5 months until I moved out to a sunnier place.","Every time they've cancelled the static fire, it's for a reason they've found not to do it. It's small, incremental steps and they knew it would take this many to get there.\n" +
            "The point is that with the government shut down they cannot continue to make those incremental steps " +
            "anymore. It's a shame because today could have been the last of those little steps. We'll find out when " +
            "the elected officials stop acting like children I suppose.","I find this article very frustrating. What do they even mean by \"key members of the civilian workforce\"? I wish they'd include examples of what kind of people aren't working. Since I have absolutely no connection to this industry, I have no way of understanding the impact of a government shutdown on the space industry. Why is it considered reasonable or unreasonable that they halt certain space-related activities due to a government shutdown?","Hello Pedro ,\n" +
            "Thank you for your letter. It was wonderful to hear from you again. I like to run and we can run in the park every day. But we can travel to the village and we can run on the meadow at the weekend.\n" +
            "I think you will feel good in my town because you like to do sport. We have to go in the new sporthall because I want to show a new football field to you.\n" +
            "I like to watch the football game on the TV but I have visited the basketball match. I play in the volleyball team of the town. I like to swim in Balaton in my freetime. I enjoy the sport and I want to life on healthy.\n" +
            "You can find tennis field, swimming pool, a lot of gym in the town. You can run in the park and you will injoy because there are fresh air. I would like to run with you and we can run on the meadow close to town.\n" +
            "I hope we will fell good in sommer.\n" +
            "Wriete me soon. Love Zsofi\n","Dear Pedro ,\n" +
            "I must write to you because last week I saw a new film… in the cinema. I have gone with my friends to the cinema because I wanted to see the new film of my favorite director. He is George Lucas. The film takes place in the future. This is a sci-fi.\n" +
            "I know you hate the sci-fi but you have to see this film because it is very exiting and scaring.\n" +
            "I was afraid in the cinema because the film was rather noisy. You have to see in the cinema because you will not enjoy on TV. You have to invite somebody to the film because you will be afraid alone.\n" +
            "You can see a new planet, knights and lot of master. You have to see the film because you will like the music of the film.\n" +
            "Well that is all for now.\n" +
            "Love Zsofi\n","Hi Andreo,\n" +
            "I am writing you a quick email because I have just seen an excellent film and I would be happy to see it again with you next week if you want. \n" +
            "The film is “Lost Lives” and is about several young people who can’t find work and quarrel with their parents. It’s so realistic and different from the American rubbish that you usually see at the cinema. \n" +
            "Let me know if you want to see it, when we meet tomorrow at Lila’s place. \n" +
            "Lots of love,\n" +
            "Bridget\n","Hi Rikardo, \n" +
            "Fantastic news! I didn’t win the jackpot but I got EUR 5000 from that lottery ticket I bought while we were on holiday. \n" +
            "I’ve already spent about half of it. For the first time in my life I don’t owe the bank any money. I’ve also bought new shoes for the winter and a coat. You will have to see them when we meet up. \n" +
            "But as I bought the lottery ticket while we were on holiday at lake Grenberg, I would like to go there again with you and stay in a five star hotel. What do you think? When are you free?\n" +
            "Love, \n" +
            "Lorna\n","Dear Zara , \n" +
            "My family is visiting London next month from 13th – 20th December . I would love to meet you while I am in London . My dad is taking me and my brother to London zoo on Saturday 15th December . Why don’t you come too ? It would be great to see you again . \n" +
            "Love,\n" +
            "Pedro\n","Dear James , \n" +
            "Thank you for your letter , which came yesterday . It’s always good to hear from you . \n" +
            "I play the guitar quite a lot . I am not very good but I enjoy it . I often go to my friend's house and we play together . I don't go to many concerts as I live in a small town and not many bands come here . At parties we often dance and I like that ! I like rock and roll music best . I listen to a lot of music on my mp3 player . I have usually got it with me . \n" +
            "What about you ? Do you play an instrument ? \n" +
            "Write soon,\n" +
            "Pedro\n","The British relationship with food has undergone a fundamental change over the past 50 years, " +
            "and in quite a contradictory fashion. Meals were once made up of simple, local ingredients using recipes that had been followed by previous generations. Now food has become a sensory and cultural phenomenon. Food production and catering is a multi-million pound industry. Top chefs show us how to cook the most delicious 3-course meals and supermarkets provide all the ingredients we need. Yet at the same time, we are less willing to spend time cooking than was once the case and instead spend huge amounts on take-aways and ready-meals.","I’m an English teacher and I have a big family, so I have a very busy daily routine! First, I get up every day at six o’clock, get washed and dressed, and leave for work by seven-thirty. I get to school at eight o’clock. I prepare my lessons and then teach until noon.\n" +
            " The other teachers and I always eat lunch and talk together in the teachers’ room. I teach again in the afternoon and then I correct my students’ homework and tests. After I get back home, I help my kids with their homework. I have three kids in elementary school. \n" +
            "Their names are Mathew, Jon and Suzie. Then, I do some exercise, eat dinner with my family and watch TV " +
            "before I go to bed at about ten o’clock. We love to watch travel shows. Finally, I read in bed for a few" +
            " minutes before I fall asleep.\n","Despite the importance of the tourism industry to local economies " +
            "there are significant costs to being a popular holiday destination. Local cultures can suffer as the needs of the tourist are given priority. For example, local shops can be demolished to make way for larger retail developments. In addition, the negative effects on the environment are well documented. Areas suffering from scarce water, food and energy resources can see the situation deteriorate with the extra demand caused by an influx of tourists. There will often be a physical impact as well, with increases in local pollution or the effect on the eco-system of large-scale construction. More significantly, the generation of income for the local economy is often lower than envisaged. The majority of income can often go to multi-nationals such as airline companies and hotel chains.","Recent years have seen a growth in what is termed 'eco-tourism'. The aim of eco-tourism is to unite conservation and communities through sustainable travel. So what are the key elements of eco-tourism? In addition to minimizing the impact of tourism on the environment, successful eco-tourism should also raise the awareness of cultural and environmental issues amongst the local host destination and the visiting tourist. Eco-tourism should be a positive experience for the local community as well as the tourist. Finally, eco-tourism should offer clear financial benefits to local people and to local conservation issues.","It also owned their holiday home in Florida, funded the upkeep of another holiday home in the south of France, paid for trips to New York and Miami, and spent more than £100,000 a year funding Mr Faulkner's hobby of classic yacht racing.\n" +
            "Mr Faulkner, a former banker, and ex-war photographer Ms Logan contributed £1.6m of the offshore money to the \"Education Purpose Trust\" - which would then fund their four children's entire private education.\n" +
            "Mr Faulkner initially denied putting any money into the Mauritian company, but his lawyers later told " +
            "BBC Panorama that while they did not accept our assertions, they have \"now commenced dialogue with HMRC" +
            " to review the arrangements that their previous advisers had recommended\".\n","What's going on, " +
            "everybody? Josh here to talk OnePlus 5T! I'll be in the comments for a bit so feel free to give me your thoughts on what we think is the company's best phone since the original One. Also, something new for our commenters - select top comments could get a shoutout in my next video, so keep the conversation going and hit the thumbs up for your favorites!","Latest figures show that the UK ready-meal industry is experiencing continued growth despite the recent economic downturn. And the reason for this success? Time-poor consumers continue to want exotic, convenient, mealtime solutions whilst at the same time being cautious about over-spending on take-aways and trips to the restaurant. And the future looks even brighter for this industry with innovative and niche sectors opening up to cater for as wide a range of tastes as possible. And which meals are we eating? Italian remains the favourite cuisine closely followed by Indian and Chinese.","Recent research into the attitudes of motorists shows we are still more than happy to get behind the wheel. Despite rising fuel costs, insurance premiums and frequent traffic jams, 9 out of 10 of us still enjoy driving. Whether it’s visiting friends and relations, taking the family for a day out or even commuting to work, the car remains first choice for many people. Experts argue that unlike public transport, the car leaves us in charge of our own destiny, giving us the freedom to travel when and where we want. The car also gives us the opportunity to express ourselves. The kind of vehicle we drive tells the world something about who we are or what we aspire to be. Cars are not simply a means of transport but also something we wear.");
}
