package Util;
import java.util.Arrays;
import java.util.List;

public class C1_Texts {
    public List get_texts(){
        return texts;
    }

    private List<String> texts= Arrays.asList("I think that this kind of advice can be detrimental to people like me. It basically says force yourself to study 5 hours a day no exceptions. If you get a job or other extracurricular activities don't count it as work time.\n" +
            "Well, I lived that lifestyle in high school. I studied 4 hours a day, limited every extracurricular activities to not interfer with my study time. At the end I believe I have missed a great portion of my life and it was not worth it.\n" +
            "Studying everyday is a great goal to aspire for, but no way you need to study that much every day. Go to classes with the textbook, mark the areas the teacher lectures about. Take notes during class. Once in a while review the book and your notes. In the meantime make thought experiments, try to apply the information you learned on imagined cases you made up for fun.\n" +
            "There is only so much willpower you can tap into. Once that is over you basically drift not being able to do anything. It is much better to live a balanced life and never put yourself into impossible workloads for a prolonged time.\n" +
            "Another point is that these kind of study hacks work for people who can already study. If you are a procrastinator in soul (a deep procrastinator in Newport's terms), this advice won't help you. If you're procrastinating heavily your mind is trying to tell you that what you're doing is pointless.\n" +
            "One powerful weapon to fight it is to keep an agenda. Plan your day before (for example using org mode or a simple paper agenda). Set very small goals and always reschedule if you need to. For example 22 Jan Monday: place the notes taken during X class in a file. 23 Jan Monday: Buy the book required for Y class etc.\n" +
            "If you can keep your study material somewhat organized, you will find it much easier to begin studying. It is all about tooling like programming.\n" +
            "One last note: studying in a silent place does not always work. Especially when I'm bored, can't start " +
            "studying or mentally overwhelmed, it helps a lot to put on headphones and blast some talkshow in the background. The change in the tone and volume of the host and occasional jokes and laughter feed my stimuli seeking brain. After 30-40 minutes I can continue without listening anything.","I've been pondering what the point [nowadays] is of all these board games I played as a child. Risk, Axis & Allies, Colditz, Monopoly, Stratego (I played all these games below the recommended game). As well as PnP RPGs, card games, and collectible card games. My problem is that, at an older age, I don't regularly meet friends anymore in physical space \"just because\", and on a birthday this doesn't fly either. Things like Friday evening RPG night? No way. Heck, I don't even have the friends anymore who are into that. That's what makes an electronic game much more accessible be it single player or MMO.\n" +
            "The answer is that as a teenager, we didn't have mobile phones etc (or well, barely) and we resorted to physical games such as card games. And as a kid, it was part of being friends with schoolmates, or (as you put it) playing with my parents. So we were already enforced, pretty much, being in physical space, overcome out boredom, and bended that to pleasure in such a way that we enjoyed being with each other.\n" +
            "The point being, that these games are still solid for youth and parents playing with youth. Heck, its partly even my problem that I don't initialise card games on a birthday.\n" +
            "Being autistic and opposite sex of my kid poses challenges though. Its still a long way down the road " +
            "but while teaching them to become competitive in games and learning to win and lose seems invaluable, with a girl I'm inclined to not bother with violence or war-theme (or WWII) games. There's tons of these available, but it does pose limitations.","I wasted tons of time while I was in high school, so kudos to you for aspiring for more and trying to be productive. Respect.\n" +
            "On the other hand, don't forget to have fun! You have your whole life to be \"grown up\", but only a few years to be young and reckless, don't squander em. I feel old for writing that, but whatever.\n" +
            "Don't overwork yourself, and don't let others take advantage of your enthusiasm. Burnout is real, so make sure none of your habits put you on the path towards self-destruction. Avoid the temptation of staying up 1 or n-more hours just to finish some thing; it'll always be there for you the next day, so it's usually better for you to get a full night of rest instead.\n" +
            "In my experience, some aspects of school are overrated. It's easy to get fixated on grades, but they're " +
            "not always representative of someone's true skills. Of course, you shouldn't lie to yourself either, so strive to actually understand whatever subject you're focused on.","Here's some of my personal experience how I have learned to study better in university:\n" +
            "While reading through your material, take notes. Moreover take notes that make sense to you. Don't copy something for the sake of it if you don't understand it, try write it down in a way that reflects your current knowledge of it and how it makes sense to you.\n" +
            "Also I wouldn't probably take everything in that article word for word. I mean:\n" +
            "Do not listen to music or TV: It is virtually impossible to do two things at once if one of them is studying.\n" +
            "sound just silly, okey I listen to calmer music when I study but should you always advocate for total ruthless silence? I think there's other aspect overlooked by the writer(s) that you should try to make studying enjoyable or at least tolerable.\n" +
            "Of course in a way it is similar to straining yourself in physical exercise and more you do it the better you get at it but at times studying hard leaves you only depleted and uninspired about the work you do. I used to do studying in a group which while entertaining didn't really at times help me to internalize the material. Now when I do mostly self-studying I can internalize really well but the solitude is kinda boring at times. Until you get into the flow and really start digging what you are doing at least.\n" +
            "But my advice to anyone who wants to study better is to take it seriously. Take notes from your material. Write down mind-maps or whatever from the concepts to help you visualize them. Use Youtube to find lessons if you feel the material is too abstract. Ask questions from people smarter than you (if there is anyone around). Implement your own solutions about problems you care about (if applicable). The mental border I see when people study is that some just want to pass the course and get perhaps a good grade. How I have started to study is I want internalize the key-concepts so well that I can use them. That means that I might spend ridiculous amounts of hours on some basic concept until it makes sense to me. At times that might cause me to miss on couple other concepts but that's the trade-off I'm willing to make.\n" +
            "After you have studied the subject comes the hard part that is actually maintaining that knowledge. This" +
            " is where I think having learnt key-concepts well really helps as you have those couple key-points to which you can return to quite easily. On the other hand if I didn't try to apply the concepts to something concrete I'll probably forget how those abstract ideas were ever linked to \"reality\".","In my essay I’d like to write about my opinion and change after my ERASMUS life in Norway. To my mind usually people dream about abroad but they are afraid to do something to take a step to move and they just act tourist but never try to work. Hungarians are skeptical against “dreams”.\n" +
            " I was lucky and chosen (the only one student from Hungary) who got a place in a small town in Norway, Halden to study. Norway is a colorful country with many migrants. Nowadays I heard from Norwegians that they personally do not really accept immigrants anymore, because they are “stealing” the jobs away. To my mind students are rather those people, who are enough brave to risk a travel and living – to try to start a new life abroad.\n" +
            "There is not just only one opportunity to move abroad. Also a work-exchange is possible. It’s chooseable: either 1 or 3 years you can choose. In Halden I became real good friends with some Italian, Swiss, American and Japanese doctors at an international “Reactor Project”. Usually exchange-workers are around the age of 30. \n" +
            "Actually foreigners have stereotypes about incoming workers. However Norwegians are quite intelligent – everyone speaks English like a native – they do not really know about Hungary. But at least we are not muslims and do come from Europe – we are accepted there. \n" +
            "I think if someone did at least a year abroad, it also might high up the level of his/her intelligence – that’s why they have more chances to get or to keep a job. \n" +
            "Language is a quite important part of the globalization. If someone can talk in a main language (English, German, Spanish, etc.) and in addition some in small ones (Hungarian, Finnish, tc.) he or she has much more chances at every field of (global) work. \n" +
            "Hungary always had the chance for exchange as a student: earlier in the Sowyet Union, now almost on the whole Earth. With the European Union and the Shengen we also have the opportunity for an exchange work of internship. \n" +
            "I feel lucky with my start of life: my mother tounge is German, I learned Hungarian in the kindergarten and I became addicted to languages, started to learn Finnish and English, I moved to Norway and I learned Norwegian there. Now I speak 4 languages fluently and one (Finnish) just on the basic level. If someone makes a time abroad, he/she is going to be open for other languages and cultures. This point we’ve got to highlight well, because multiculturism just started recently – and it ain’t stop. \n","In my journal today I’m going to write about my opinion about a topic (after a webpage) about potential virtual schools in the following century. \n" +
            "As I was learning at the elementary school, teachers always forced us to work in teams. I never liked it – it did disturb me all the time that I’m the only one in the group who takes the given work serious. I liked reading lessons and homeworks – also I liked the test – because they’ve been rather individual and independent. Later I recognized that it also can make fun and right now. I believe that cooperation is always needed. I do not really think that it’s possible to study by our own. Psychologically people need friends. Also it might be a kind of aim to be under people, to learn cooperating with people for kindergartens and schools when we get out into the life of workers we could give the expected niveau of work. \n" +
            "To my mind only literature is that subject that can be tough electronically With a webcam and a software like Skype is enough. But in maths, biology and any other classes children need the teacher to be attend. They need someone who walks along the tables and checks and corrects their daily work. If it happens as the author on that homepage explained, the student-student (I might risk to say also friendship) relationship and the student-teacher relationship will be slowly disappearing. In this case people ain’t feel love for others, it’s going to be harder to get a partner. I also can imagine that people are going to look for their matches on webpages, they’ll get engaged, married – but they’re never really going to love each but just their kid.\n" +
            "And a child, with no family that can show the needed amount of love, can also become dangerous to other people. \n" +
            "The electronic learning already started – as I recognized it in Norway as I’ve been studying there. In my class we’ve been 7, but I’ve been attend always alone, because my classmate were doing electronical job. I also got many tasks that I should record my essay and handle it in the format of “mp3” in. To my mind it’s a good way at languages to correct the accent.\n" +
            "I have plenty of plans with my children and their children and it doesn’t really contain internet. But like the article they’re gonna get in the middle and learn on a well required niveau. \n" +
            "It’s not a piece of cake to learn by our own. There is not going to be any motivation (heard from a classmate for example) and it parents don’t care, their child is going to fail at school and later at life. \n" +
            "But the most important thing at studying-home is the lack of the realizing about the beautyness of the world. No matter what people do in their free time but it they don’t have friends, they do not really organize trips in the nature – they’ll forget about it and slowly the interest for each and the Blue Planet will disappear.\n","One of the main objectives of education is to prepare children for work . In order to help a country grow economically , schools are encouraging students to study science , economics , computer skills , business and maths . Creative subjects like art and music are considered less important . However , I believe that they should continue to be taught in schools.\n" +
            "Music courses often include several different strands . At my school , the music course includes performance , music theory and composition . Each of these areas teaches a child different skills . Performing teaches children confidence . Music theory teaches analytical and mathematical skills . Composition allows students to be creative . Although it is true that many students who are interested in music take classes outside school , many young people do not have this opportunity because their parents aren’t musical . That’s why we need to continue to provide music lessons at schools.\n" +
            "Another creative subject under scrutiny is art . But art is everywhere in our society . It is in the clothes we wear and in the design of the products we buy . School art students go on to become illustrators, designers and architects . Also , creative people are often successful in other fields such as teaching and business . We need to encourage young people to think creatively and school art lessons are important in this way.\n" +
            "To conclude , I think it is very important that schools continue to teach creative subjects such as art and music as well as those subjects that are considered more important for the country’s economy . Not all young people get the opportunity to explore their creative sides out of school , and confident , creative people are equally important to a country’s economy as economists and scientists .\n","Hi Louisa , \n" +
            "Thanks for your email . I’m glad you can join us for the weekend away . There are indeed still free places , so your sister can come if she wants . I think the theme park has some rides for children , but my friends and I are definitely going to spend the day on the big rides , so your sister might have to spend time alone with Maddy , and so she might feel a bit left out . There is a twin room free that your sister and Maddy can have . Your sister will have to be careful with Maddy because there’s a lake on the site and we wouldn’t want Maddy to fall in .  It gets quite muddy there and it will be getting dark when we arrive , so your sister had better not let Maddy run off . As you know , I’ve booked a night out at a curry restaurant and a bar in the evening , and I don’t think that’ll be suitable for Maddy . She’ll probably need to be tucked up in bed by that time . Your sister will have to stay at the cottage alone to look after her , unless you’re happy to stay in and keep her company . So , in short , your sister is welcome to come , but it might be a bit boring for her at times . \n","While you are in Westbury , you must visit the White Horse Country Park . The park is situated on the top of a hill overlooking the town , and has magnificent views across the countryside . The famous white horse , a chalk symbol which can be seen from many miles away , lies on the side of the hillside . The park is also the site of an Iron Age fort , and everyone , from young children to adults , can enjoy climbing on the banks and can even roll down some of the gentle slopes . If you have a kite , bring it along because there is often a strong breeze on the hill . There are a number of paths around the park where you can take in the view . These may not be suitable for people with pushchairs , wheel chair users and people who are unsure of their footing . After your exertions , you can enjoy an ice cream from the ice cream van which is always present . The easiest way to get there is by car . Just leave the town along the Bratton road and take the road on the right next to the pottery shop . The road is well signposted . If you don’t have a car , you can get a taxi . A trip will cost about £5 from the town centre . Otherwise it’s a steep , 45-minute walk . Entrance to the park is free of charge .","Dear Sir / Madam , \n" +
            "I read your advertisement in Students International and I would be very interested in volunteering in the sporting event you are organising . I am a French student and I have been studying English for eight years . I have taken part in several language exchange visits to the United Kingdom , so I can communicate confidently and quite fluently in English in social situations . I also speak a little Italian and German . \n" +
            "I believe that I have good personal qualities which make me an effective volunteer for your event . I am outgoing and enjoy meeting people from different cultures . I have played in the college volleyball and football teams for over four years , so I am used to working with other people and encouraging them in our shared endeavours . I also have work experience in working on the front line with customers . I work at weekends in our local supermarket , which requires me to deal with customers with a pleasant attitude and liaise with other staff . I have also worked as a receptionist in a hotel in the south of France as a summer job . Here , I had to welcome guests and deal with any problems which arose . I can send you references from these employers if you need them.\n" +
            "Thank you for your interest in my application . I look forward to hearing from you .\n","Thank you for giving me the opportunity to give feedback about my experiences at Brightwell College. Firstly , I’d like to talk about the teachers , who were excellent . They prepared us very well for examinations , and it’s down to them that so many of us obtained good grades. We always had the opportunity to discuss our ideas in class and the teachers never dismissed our ideas , no matter how strange they were ! Having said that , the homework workload was very high. The teachers were very strict about handing it in and rarely gave us extensions . Although I realise that homework is important, I do feel they could have been given less homework and been less strict about deadlines , as this often prevented us from getting involved in sports and clubs and having evening jobs. Furthermore , although the teaching was excellent , the facilities were not. The text books we used were very outdated , the library did not have enough desks , and there were not enough copies of important books . There were also not enough computers for the whole class to use at the same time . Socially , there were a lot of sports and music clubs to join , but very few others . I would have been interested in taking extracurricular classes in drama , woodwork and cookery but these classes were not available , which was disappointing . Secondly , the school organised very few outings except for a few geography and biology field trips , and I would have liked the opportunity to go on activity holidays with my classmates , such as ski trips or adventure sport weekends","I would like to respond to your request for money-saving tips for students . As I see it , there are two main things that a student needs to think about : how increase your income , and how to reduce your outgoings . \n" +
            "Getting a part time job is really worthwhile when you’re young . Not only does it bring money in , but it will impress future employers . Find a job which fits into your schedule . Many shops offer Saturday jobs , while you can get jobs at bars and restaurants in the evening . There are also lots of holiday jobs available in hotels , holiday camps or on farms . \n" +
            "Secondly , you need to decrease what you spent . If you cook for yourself , buy value products and avoid ready-made meals . Share cheap recipes with friends . You will save money on food and energy bills if you buy food and cook it in bulk , so get together with friends and share the cooking . When shopping for clothes and utensils , buy second hand from markets or from online auction sites . Just don’t get carried away ! It’s easy to spend a lot when things are cheap ! \n" +
            "Of course , you don’t want to stop spending altogether , or you will never have any fun ! So it’s important to prioritise . Decide what’s important to you , whether it’s sports , travel , good food , nights out or nice clothes , and put enough money aside for that . Then you can scrimp and save on the things that you consider less important .\n","Dear Sir/Madam, \n" +
            "I attended a twenty-four hour per week course for two weeks in July at the Heaton School of English. I am writing to you because I understand that this school is accredited by your organisation. \n" +
            "The standards of the school fell short of those expected from an accredited school and those which were advertised by the school. \n" +
            "The school promised qualified and experienced native English teachers. In reality several of these teachers had not taught before and lacked any knowledge of pedagogy. The classes were made up of a random selection of students: different ages, abilities and reasons for studying English. \n" +
            "I was promised in advance a course to prepare me for examinations but this was unavailable, so how the school can boast of a high exam pass rate is inexplicable. The school also undertook to provide modern functioning computers; in reality the computers were both dated and often non-operational.\n" +
            "In view of this completely unsatisfactory course, in breach of both your stipulated standards and the advertising of the Heaton School, I am asking for a full refund of the course fee. I would like your advice and assistance in this matter. \n" +
            "Yours faithfully, \n" +
            "Bridget Reninson.\n","Grenberg Decongested? \n" +
            "Last week in a rainy November morning I set off from my home to drive into town, along about a quarter of the ring road in the direction of the town hall. In all, the journey is about ten kilometres; it took an hour and a half. \n" +
            "From Monday however to make the same journey I will have to buy a EUR 10 sticker for my windscreen window. Entering the ring round and the centre of the town without a sticker will cost EUR 100 in an on-the-spot fine. \n" +
            "Congestion charging has been proposed for years, but when Arnie Fischer was re-elected mayor for a third term in April, he gave an explicit promise to promote the charge. As he pointed out yesterday in the Grenberg Times the charge ‘will lessen congestion and raise money for public transport.’ Fischer has allocated an extra EUR 1 million to upgrade the bus and tram network. \n" +
            "The campaign Grenberg Free Roads has mounted an on-going battle against road charging. Group spokesperson, Edgar Grice, told me yesterday, ‘We are going to challenge this law in the courts. Nobody is going to make me pay for using the public roads.’ Perhaps Mr Grice will be among the first people to pay the EUR 100 fine. \n" +
            "An opinion poll last week showed an overwhelming backing of 86% in favour of the charge.\n","Two very different plays are currently being shown at Grenberg’s Playhouse this week. \n" +
            "For those who enjoy romantic comedy, you shouldn’t miss Ben Gold’s “It Happened to Me” featuring young Sarah Jenner as the incurable romantic Jude Smith. Producer, Hermann Shils has made several innovations on the original play, nearly all of which have added to the humour and flow of the performance. Also don’t miss an excellent performance by the slick and well-casted Jeremy Fletcher as the hapless Alfie. \n" +
            "Tuesday and Friday are given over to heavy-going “Death in the Morning” by local playwright, Miriam Pink. The protagonist, Elsa, is played by the talented Gertrude Horn who has made this tragic role her own. Some commentators doubted whether Pink could produce this performance of her own play, but she seems to have effortlessly made the transition from playwright to producer. \n" +
            "Seats are selling fast for “It Happened to Me” which has the edge on popularity, though, while singing the praise of both plays, I would say “Death in the Morning” is the better drama. But why not treat yourself to two theatre outings this week?\n","‘Stereotypes help us understand the world.’ \n" +
            "Stereotypes, as forms of generalisation and the abstraction of the key features of things, are necessary for understanding the world around us; however the blind use of stereotypes can lead to misunderstanding. \n" +
            "If, for example, you imagine every type of chair in the world you have an array of thousands. Yet to all these entities we apply the stereotype – or label – chair. If somebody asks us what a chair is we don’t start by listing everything that is a chair. Instead, we utter some key features of a chair which in our view characterise all chairs; e.g. a surface for sitting above the ground. \n" +
            "What applies to chairs of course applies to everything else in the world that we think about: a family, a government, bad behaviour and so on. What then are the dangers in this mode of abstraction? I will mention two. \n" +
            "First, and perhaps most important, is when we assemble stereotypes according to prejudicial thinking. In the past, and among some people today, concepts are constructed according to false stereotypes; e.g. labelling certain work as women’s or men’s work. \n" +
            "Second, is simply when we define our stereotypes too narrowly or widely to make them useful. An example of the former is defining a chair as having four legs. Why can’t a chair have three or four? An example of the latter would be defining a chair as something that can be sat on. Well a tree trunk can be sat upon. \n" +
            "In conclusion, stereotypes are useful but should not be used lazily.\n","Dear Sir / Madam , \n" +
            "I read in last week’s edition of the White Horse News that you are keen to reward local people who have made significant contributions to the community . I would like to put my mother , Mrs . Gillian Summerton , forward for this reward . \n" +
            "My mother is a schoolteacher , and has done much to enrich the lives of the young people in her care . In her free time , she continues to give up her time to help people . She runs a ladies’ choir which is a superb opportunity for local women to get together and enjoy themselves . Moreover , the choir performs free of charge at charity events , and consequently my mother has been fundamental in both raising large sums of money and bringing pleasure to people . \n" +
            "I know that my mother does not need a financial reward for her services to the community , as it gives her a lot of pleasure . However , I’m sure that she would appreciate formal recognition for her work , perhaps in the form of a donation to her preferred charity , the Red Cross . \n" +
            "Thank you for your attention.\n","Dear Sir/Madam , \n" +
            "I am writing to you regarding the new HD television I bought from your shop last week . Please find a copy of my invoice attached . \n" +
            "After I set up the television it seemed to be working fine and I was very pleased with my purchase . However , during the evening , after the TV had been on for a couple of hours , a line started to appear across the centre of the screen . I tried changing channels but the line did not go away . At this time , the sound from the television became a little distorted . This was about 3 days ago now and since then the problem has got worse . There are several lines across the screen and it's almost impossible to understand any of the audio . \n" +
            "As I'm sure you can appreciate , I'm extremely reluctant to disconnect the TV and bring it back to the shop , and I'm not sure that I should have to . So I would like to know how you suggest we resolve this issue . Perhaps you could start by sending an engineer to my house but if they cannot solve the problem I expect a replacement , and for it to be delivered . \n" +
            "I'm looking forward to your prompt reply . Yours faithfully \n" +
            "Carl Hansford.\n","Mobile phones have transformed the lives of nearly everyone on the planet in the last few years . They have made communication easy and cheap between friends , family and businesses . The phones are not only used for speech and text messages but increasingly to browse the internet , to read email , to play games or to pay for products . In many countries , particularly those with slow network connections , the internet is something that happens on a mobile phone rather than on a computer . \n" +
            "There are also disadvantages to using mobile phones . One is the potential health risk . While the information is not conclusive some people living near to mobile phone transmitters report higher rates of cancer then elsewhere . Keeping a powerful device transmitting waves and heat next to your ear for long periods of time may be harmful to heavy users of mobile phones . There are also social problems related to mobile phone use . Walking around with a phone glued to your ear may prevent you from interacting with other people while anti-social use on public transport or in the cinema has led to many public environments , such as theatres and cinemas , requesting users to switch their phones off or to silent . There are also technical issues with mobile phone use . Many areas do not have network connectivity and the reliability or audio quality of the mobile service in other areas may fall well short of that provided by a landline . \n" +
            "Significant those these drawbacks may be , the huge convenience of the mobile phone will ensure that its" +
            " use continues to change our lives.\n","The idea that both parents should contribute actively to bringing up their offspring would seem hard to dispute . This does not mean however that all tasks in the child rearing process should be shared equally . \n" +
            "The idea of tasks being shared equally between parents contains several assumptions . One assumption is that both parents have equal amounts of available time and are both available to do what is required at the time it is required . Clearly this is often not the case . If , for example , a child needs help with some homework one evening and one parent is required to work late , the task falls to the other parent . Therefore , despite genuine attempts to share duties equally , it will not always be practically possible to do so . \n" +
            "The second assumption which is implied by the idea of sharing tasks equally is that both parents are equally well prepared or skilled to do all tasks . Again this is clearly not the case most of the time . For instance , it may be that the mother is a teacher and able to provide the kind of support the child needs with their homework more effectively than the father . \n" +
            "In theory , perhaps the best approach would be to first decide what the child needs at any given time , and secondly to assess which parent is in the best position to provide this need . This approach is aimed at using the parental resources most effectively , rather than 'equally' . \n" +
            "In conclusion , it would seem that the 'equality' point of view may not always be in the child's best " +
            "interest . A more effective approach might be for couples to agree on how they can best use their resources . Even if this is accomplished however it is unlikely to be achievable constantly due to practical restraints .\n","We often hear that new technology is in conflict with our traditions . The new is replacing the old . Are there any ways however in which new technology can help support our traditions and help keep them alive ? \n" +
            "First of all , it seems that technology can help preserve our traditions by providing a channel of education for them . For instance , the Internet is now an established provider of education . From a good website we can learn a lot about our past and our traditions . This can be brought to us in interesting ways if the website has interactive learning activities . In addition , this technology can be made available in our schools , and homes , quite easily . \n" +
            "A second way in which today's technology can help is by keeping us informed . Our traditions are kept alive by us continuing to carry them out and celebrate them . Again as a result of the Internet , and mobile phones , it has never been easier to inform people of upcoming events and to spread the news to a large number of people quickly , easily and at little cost . \n" +
            "Finally , it could be argued that modern technology saves us time . We can do a lot of tasks much more quickly than in the past . In theory therefore we should have more time to devote to traditional activities . Whether we choose to do so or not however rests with the individual . \n" +
            "In conclusion , there would seem to be several ways in which new technology can help us to preserve our " +
            "traditions particularly by educating and informing us . As in many other aspects of our life however , " +
            "it is up to us if we decide to employ the technology in this way or not .\n","For all the people who " +
            "feel sad buying the OnePlus 5.....I still use my OnePlus 3T ( although i can afford any phone  on the planet ) WHICH after 1 year is as fast as when I bought it. People are unnecessarily Upgrading & wasting money. Before buying, Upgrading ask yourself this. Is your phone working just fine ? Is there a need to upgrade to the latest ? Now you buy OnePlus 5T & 2 months later Samsung in January will announce galaxy S9 in Mobile World Congress. And then you'll feel the SAME WAY as you feel NOW. Then after you buy it, OnePlus releases OnePlus 6 in May/June & will want to buy it. And then a few months later, the iPhone 11 & OnePlus 6T arrive. My point is, if your phone is working perfectly, just stick with it & be content. This is a never ending process by companies to milk the money out of customers. I have seen very successful & rich people still using their iPhone 7+/6S+. When asked why, they simply said \"it's working fine\". And they replied in such a way as if they DIDN'T EVEN CARE ABOUT such a small thing. Tells you something about WHY they're successful in the 1st place doesn't it ? Be content with what you have as long as it's getting the job done. And focus on MORE productive things .\n","I am writing to request your authorisation to attend a 5 day seminar on *effective ways of improving written communication* *within the Health Insurance Sector* as instructed by my team leader Mrs. Murray. It will take place during the last week of next month, from 26th to 30th of June at the Olympia Convention Centre and its  fee is EUR 200. \n" +
            "The seminar entails  strategies to enhance clarity and avoid miscommunication, not only between company and clients but also between departments. The approach takes into consideration the worldwide background of clients  which is very relevant to the focus of our company. \n" +
            "After working for over 3 years in the operations team and having participated of various cross departments  meetings, I have noticed that communication issues are still at the core of the delay in resolving client’s problems promptly. Therefore, I strongly believe that attending this course will boost my confidence at work as it will provide me with extra tools to understand and tackle this issue. \n" +
            "Upon completion of this seminar, I would be happy to devise a short course for my fellow colleagues based on the most important points learned from it  which I strongly believe that  will benefit our department and as a result maximise even more our client retention number  \n" +
            "That said, I am aware that my colleagues will be under extra pressure to cope with our additional work load while I attend the seminar. Despite that, I still think that it will be worthwhile to the company and me on the long term. \n" +
            "I would highly appreciate your approval and look forward to hearing from you at your earliest " +
            "convenience.\n","As requested, this is a report about crime rates in Maryland Heights and young people's attitude to the problem. 200 young people aged 18-25 were asked to share their opinion on the current crime situation. The results of the survey are presented below together with recommendations on how to solve existing problems. \n" +
            "Mugging and assault \n" +
            "Physical violence is the most frequent crime being committed in the area. 20% of those questioned reported having been either assaulted or mugged. Young people complain of certain areas to be  particularly dangerous due to the absence of proper lighting and reliable security. Therefore, it is advised that additional street lamps and surveillance cameras should be installed and police patrolling the streets should be organized. \n" +
            "Drug dealing and gangs \n" +
            "Another problem that the community is facing is that of drug dealing. It is rooted most likely in the gang activity in the town. The members of the gang choose their targets among schoolchildren and students – 10% of the latter confirmed either being offered drugs or having seen others being offered To stop it, we suggest monitoring the gang more closely and making arrests whenever drug dealing is suspected to take  place. Besides creating comfortable conditions for people to be able to report drug dealing safely and anonymously could also help in eradicating the danger.\n" +
            "Conclusion\n" +
            "The survey showed that on the whole young people are reluctant to consider the area safe, which means " +
            "that high crime rates and their causes should be investigated further for more sufficient details. Meanwhile, safety measures suggested above could be implemented to change the situation for the better as quickly as possible. We hope that this report will receive your serious consideration and necessary steps will be taken in the near future.","Cars are one of the most popular means of transport nowadays. They are used everywhere in the world by people of different income, age, social status and occupation. This essay deals with the question of driving a car, summarizing and evaluating the ideas expressed in the texts above. \n" +
            "Both texts speak about personal transport, but they analyze the question from different angles. The first passage rises  the problem of traffic congestion and names two possible ways to solve it: restrictions on speed limits and parking on the one hand, and promoting alternative means of transport on the other. The ideas expressed in the text are certainly true for large cities where traffic jams are one of the biggest concerns. However, the situation in small towns and rural areas is totally different: the problem of congestion does not exist there and thus does not need to be solved. \n" +
            "Unlike the first text, the second one looks on  the positive side of driving. Calling driving a  most " +
            "popular means of transport and providing statistics to prove it, the text gives the reason for cars popularity. According to the passage, having a personal vehicle gives people a (-) freedom of choice and a way to express themselves – things which outweigh all the disadvantages like  high cost and traffic inconveniences. It is hard to argue that driving a car is popular, but I believe that its popularity is rather due to comfort than to human psychology.","The impact of the media on teenagers\n" +
            "Nowadays it has become almost impossible to ignore the media due to the fact that most of us spend some daily time either watching television, listening to the radio or surfing the internet. Specially teenagers who spend a significant part of the day exposed to all types of advertisement. Advertisers consider that teenagers are the perfect target, while some people believe that teenagers have changed marketing worldwide.\n" +
            "Who manipulates who? That is the dilemma.\n" +
            "On one hand, the marketing and advertisement industry look upon the young generations as the easiest people to influence. Making them believe that certain items are the key to popularity is the strategy they have developed to sell among that generation.\n" +
            "On the other hand, some people believe that advertising responds to young peoples‘ desires and not the other way around. It is the energy of teenagers that has had a huge impact on this industry, making it more innovative and creative. The power of young people have push advertising boundaries to become almost an art form more sophisticated and attractive than ever before.\n" +
            "All in all, there has been a revolution in the adversiment industry globally. While some people may be " +
            "influenced by it, some others may deﬁne trends. Ten years ago people were not so worried about material offered by the media. Globalization has changed everything, advertising has become part of our daily lives and it is unavoidable. The temptation surround us, some of us fall for it.","Concern is often expressed about the negative effects that television can have on young people. As far as l am concerned, the rnost serious damage that occurs is a result of the constant commercial pressures that vulnerable youngsters are exposed to.\n" +
            "Advertisernents every ten minutes or so as children and teenagers watch their favourite programmes are likely to lead them to believe that possessing the latest gadget or item of clothing will bring them happiness and respect from others. To my mind, the result ofthis can only be a generation whose values are too materialistic for their own ultimate contentment.\n" +
            "This is not to say that all advertisements are lacking in quality. It is not unreasonable, in fact, to consider them as an art forrn as many are imaginative and make original use of language, music and camerawork.\n" +
            "They are indeed often produced bytalented young people who ﬁnd them an appropriate focus for their own creativity.\n" +
            "ln my opinion, the answer lies in education. Advertisements are not harmful per se; it isjust that we " +
            "all need to know how to use them. We should take the information that we need from them but we should be aware of the techniques that their makers use with the hope of influencing us to buy things we do not really have any need of. Young people should be taught not only to appreciate the artistic qualities of adverts but also to recognize the tricks that are being employed. Greater sophistication should lead to less vulnerability.\n","The televised national event to be dealt with in this report is the royal wedding that took place in London in 2O11. It was the wedding of Prince William to Kate Middleton. The ceremony took place in Westminster Abbey and was a spectacular occasion with plenty of ancient gilded carriages, men in uniforms hung with medals and ladies in extravagant hats. The British media makes a great fuss of such occasions and there had been considerable press interest in the event from the moment the couple's engagement was announced.\n" +
            "On the day there was TV coverage of the wedding from start to finish. The public saw the streams of guests arriving. They could watch the groom nervously talking to his brother before the ceremony. They were shown the bride leaving her central London hotel. They saw the entire ceremony and the procession afterwards. The TV coverage could be said to have made the public feel as if they were in a sense wedding guests themselves.\n" +
            "In general, TV did help this wedding to create a mood of national celebration. There was so much on TV " +
            "in the days leading up to the wedding that many people were tired of it before it had even begun. However, once the ceremony itself started it was hard not to be drawn into it. This was a royal wedding but it had an ordinary feel to it somehow. Despite the cameras the central figures appeared relaxed and made their vows without faltering. They giggled slightly as the groom struggled to get the ring on his bride’s finger: lt felt less stiff than previous televised royal weddings perhaps because the bride was a middle—class girl from a family that it was easier for most people to relate to than had usually been the case with royal spouses. Viewers were moved by this wedding and the way it symbolised — as all weddings do — love and hope.","Shakespeare in Love is a romantic comedy that circles around the forbidden love of William Shakespeare and Viola de Lesseps, the daughter of a wealthy merchant. The relationship between Will and Viola is based in poetry and inspiration making it strong and interesting.\n" +
            "First of all, Viola appears to be in love not only with Shakespeare but with his powerful writing as well. We can clearly see this in the scene when a play is performed for the Queen and Viola attends it, she whispers the lines written by Will being absorbed by them and loving every word of his poetry, before even falling in love with him. Viola is attracted to Will as they have a common passion for poetry and theatre. We can see her devotion to both when she forces Will out of bed to write the next page for them to practice that day.\n" +
            "Moreover, at the beginning of the screenplay we see Will searching for a muse, characteristically referring to it to Henslowe as “an emptiness that seeks a soulmate” when he desperately asks for his pages. However, falling in love with Viola is the answer to his “writer's block\", as through their forbidden love he finds the inspiration and weaves his life into the plot of “Romeo and Juliet”. Consequently, many of his and Viola’s quotes take their part in the play Will is writing, as captured in the bedroom scene. The inspiration he draws from Viola is unreplaceable and that is what makes their love so deep and passionate.\n" +
            "To conclude, Will and Viola both make their dreams come true through this love, for Viola is being an " +
            "actress, something forbidden for women at the time, for Will it is writing a powerful play and becoming " +
            "a significant playwrite. Their love arms them with everything necessary to fulfil these ambitions and live passionately for the time they are together.\n","Internist Gail Povar has many female patients making their way through menopause, some having a tougher time than others. Several women with similar stories stand out in her mind. Each came to Povar’s Silver Spring, Md., office within a year or two of stopping her period, complaining of frequent hot flashes and poor sleep at night. “They just felt exhausted all the time,” Povar says. “The joy had kind of gone out.”\n" +
            "And all of them “were just absolutely certain that they were not going to take hormone replacement,” she says. But the women had no risk factors that would rule out treating their symptoms with hormones. So Povar suggested the women try hormone therapy for a few months. “If you feel really better and it makes a big difference in your life, then you and I can decide how long we continue it,” Povar told them. “And if it doesn’t make any difference to you, stop it.”\n" +
            "At the follow-up appointments, all of these women reacted the same way, Povar recalls. “They walked in beaming, absolutely beaming, saying, ‘I can’t believe I didn’t do this a year ago. My life! I’ve got my life back.’ ”\n" +
            "That doesn’t mean, Povar says, that she’s pushing hormone replacement on patients. “But it should be on the table,” she says. “It should be part of the discussion.”\n" +
            "Hormone replacement therapy toppled off the table for many menopausal women and their doctors in 2002. That’s when a women’s health study, stopped early after a data review, published results linking a common hormone therapy to an increased risk of breast cancer, heart disease, stroke and blood clots. The trial, part of a multifaceted project called the Women’s Health Initiative, or WHI, was meant to examine hormone therapy’s effectiveness in lowering the risk of heart disease and other conditions in women ages 50 to 79. It wasn’t a study of hormone therapy for treating menopausal symptoms.\n" +
            "But that nuance got lost in the coverage of the study’s results, described at the time as a “bombshell,”" +
            " a call to get off of hormone therapy right away. Women and doctors in the United States heeded the call. A 2012 study in Obstetrics & Gynecology showed that use plummeted: Oral hormone therapy, taken by an estimated 22 percent of U.S. women 40 and older in 1999–2000, was taken by fewer than 12 percent of women in 2003–2004. Six years later, the number of women using oral hormone therapy had sunk below 5 percent.\n","Now there’s a way to tell if a drone is spying on someone.\n" +
            "Researchers have devised a method to tell what a drone is recording — without having to decrypt the video data that the device streams to the pilot’s smartphone. This technique, described January 9 at arXiv.org, could help military bases detect unwanted surveillance and civilians protect their privacy as more commercial drones take to the skies.\n" +
            "“People have already worked on detecting [the presence of] drones, but no one had solved the problem of, ‘Is the drone actually recording something in my direction?’” says Ahmad Javaid, a cybersecurity researcher at the University of Toledo in Ohio, who was not involved in the work.\n" +
            "Ben Nassi, a software engineer at Ben-Gurion University of the Negev in Israel, and colleagues realized that changing the appearance of objects in a drone’s field of view influences the stream of encrypted data the drone sends to its smartphone controller. That’s because the more pixels that change from one video frame to the next, the more data bits the drone sends per second. So rapidly switching the appearance of a person or house and seeing whether those alterations correspond to higher drone-to-phone Wi-Fi traffic can reveal whether a drone is snooping.  \n" +
            "Nassi’s team tested this idea by covering a house window with a smart film that could switch between transparent and nearly opaque, and aiming a drone with a video camera at the window from 40 meters away. Every two seconds, the researchers either flickered the smart film back and forth or left it transparent. They pointed a radio frequency scanner at the drone to intercept its outgoing Wi-Fi signals and found that its traffic spiked whenever the smart film flickered.\n");
}
