package Util;
import java.util.Arrays;
import java.util.List;

public class C2_Texts {
    public List get_texts(){
        return texts;
    }

    private List<String> texts= Arrays.asList("My older brother is deaf and I remember my parents talking about how the greatest difficulty wasn't in THEM coming to understand him, but getting anyone else to. Their only options for a deaf child in the late 70s early 80s was an underfunded, unpleasant and depressing state school that, in reality, functioned more like a state orphanage or choosing the aural lifestyle for him and, in a sense, trying to force to him to be hearing.\n" +
            "Fortunately, right about the time when this dilemma was facing them, the law was passed down that local school systems would HAVE to cooperate with children that had special needs for the their education. Knowing my brother, knowing the struggles my family went through and how it affected us, really drove this movie home for me. I can say without any trepidations that I absolutely loved this show so much. Not only did it NOT portray a deaf person as being \"Special,\" it also made the point of showing that the real problems for a deaf person in their life doesn't come from their own deafness but how much of society itself simply doesn't know how to react to them. My brother is smart, he's creative and a little nuts. Ok, I take that back, he's REALLY nuts and has made some dumb decisions I don't agree with. But that's the point. My brother's deafness is not his defining trait. It's simply one facet of his personality.\n" +
            "Nishimaya demonstrates that simple but often missed part of being deaf. Being deaf doesn't define her. " +
            "She is intelligent, competent and has a clear personality. This is not \"Despite\" OR \"Because\" of being deaf. It is simply one part of her character. The challenge of interacting with the Hearing is a central part of this story and really drives home the point that the people around her chose to define her BY her deafness. Lacking a proper interpreter (I never saw one) made that a serious issue. Even the people who weren't \"looking down on her\" in the aggressive sense were instead doing it from a condescending PoV. The characters who averted this tendency were the ones who realized the real challenge in her life was the bullying itself that resulted. Her family's strain, Shoya's redemption and the ultimate tragedies in the overall story are practically-speaking, derived from the bullying she experienced. In the end, it was OVERCOMING that hangup of viewing her through the lens of being \"Special\" that allows Shoya to make himself a better person and strive to improve the lives of the people around him, including her. Nishimaya isn't a DEAF person. She is a deaf PERSON and I think this movie managed to display that properly.","One thing to understand about the US is that it is actually a federation of states. Much of the day-to-day work happens at the state or local level, not at the federal level. Police, fire departments, emergency first responders mostly employed at that level, and when the federal government is involved, a lot of it is in doing some coordination between states, setting standards, funding for various programs, and so on. Even things like building interstate highways, which are funded by the federal government, are generally done by allocation to the state governments to actually construct them.\n" +
            "However, the military is entirely part of the federal government, as are many other organizations. In the case of not having a budget, the government is required to shut down all functions that are not essential for safety and security. So things like the military, the TSA, and so on can continue to function, but office workers doing jobs like allocating the funding for highway construction are furloughed, put on temporary unpaid leave from their jobs.\n" +
            "This is, of course, terrible for the efficient functioning of government; when the impasse is over, they will have to come back to their jobs and try to catch up. Oh, and in the time leading up to the shutdown, many of them would have been busy preparing for the shutdown, documenting which functions would be considered essential and thus able to continue during the shutdown; because the deadline was no surprise, and there had been many temporary funding bills leading up to this point, there was always a pretty high chance that this shutdown would happen.\n" +
            "Of course, this inefficiency plays well into the politics of one of the parties, who hold a religious " +
            "belief that private enterprise is always more efficient than government, and so playing games like this that increase its inefficiency help to sell their case and get government functions sold off to private enterprise, who just so happen, in so many cases, to be some of the largest donors to campaigns of this particular party.","I went through university not knowing how to study, and as a result, I now have a \"worthless\" degree. One thing is, that the university and the degrees I took was a joke. 3-6 hours of \"class\" (100+ people crammed into an auditorium), no graded homework or feedback during semesters, and examns was just handing in 12-15 pages of analysis, and then getting a grade on my report sheet. No contact with educators, no counselling, guidance or otherwise interaction with lecturers, educators or other staff at the university. I could sit a home 30 hours a week and still get my \"degree\". Basically no feedback from the university on how I did, where I was heading etc.\n" +
            "For me, this means I made a lot of stupid choices. For one, I never understood the degree I took, but relentlessly kept on \"fighting\", as I thought that it _had_ to make sense to me someday. It never did. Swapped studies during my masters, but got into a \"soft\" IT-programme that didn't resonate with me either. As a result, I never learned to study, because I would get stressed out that the material never really made sense to me. I couldn't connect it to anything in the real world (and perhaps more important to me - no job postings ever seemed to ask for the skills I was acquiring).\n" +
            "Today, two years after i finished with an A+ (I wonder how...), and average grades in general, I have a galloping depression, and just wish that I could do it all over. No doubt I was perhaps immature or used to be a \"natural talent\" through high school, and therefore thought University was just passing examns. That hurts me a lot, and I have a hard time letting that thought go. I don't think anyone will ever be able to convince me, that the university or classes I went to was working as intended however. In my mind, education cannot solely be based on people reading and writing for themselves.\n" +
            "I wish someone would have shown me a guide like that when I started, and helped me manage my ambitions " +
            "and performance a bit more throughout university. I'm now a worthless member of society, even though I have a degree. I don't think anyone is happy with the outcome, but I'm pretty sure I'm the only one to blame. At least thats what I keep telling myself.","The tourism industry is in a state of flux  . Countries are competing for tourists by investing in their holiday destinations and thus making them more attractive and diverse. However, tourism needs to be carefully managed to prevent harm to the environment and disruption to local communities and its economy. The possible disadvantages of tourism on the one hand and new types of sustainable tourism on the other are discussed and contextualised in the two extracts. \n" +
            "The issues touched upon in the first text are threefold: important projects for local communities might be sidelined as the focus is on infrastructure developments for tourists, the situation in environmental problem zones may be exacerbated by, for example, water cycle damage and on top of that, the profits of tourism often are not for the benefit of the local population. Instead global players such as hotels or airlines walk off with their pockets full. \n" +
            "The flaws of tourism are contrasted by trends such as eco-tourism  which aims at reducing the impact that tourism has on naturally beautiful environments. Eco-tourism is based upon the idea that the natural environment and local communities are not exploited by tourism. All tourism projects are designed in cooperation with local communities. Infrastructure improvements have to benefit local inhabitants and not just tourists.\n" +
            "Tourism nowadays has to be seen in the context of climate change and declining natural resources. Some " +
            "remote islands or regions located on the shore may disappear in the forseeable future  due to rising sea levels. We should do our utmost to put off such a bleak scenario by travelling responsibly, avoiding long-distance flights as much as we can, protecting resources by not taking too many showers, eating local food and drink and not using air-conditioning into the bargain. It is about time we heed these guidelines. Otherwise we will be the ones experiencing the devastating consequences first hand.\n","Our society is going through a global tendency which encourages people to cook less and buy more of these  ready-made meals. The considerable growth in the consumption of convenience food has taken place not only in  UK but in many other countries, such us in Brazil. The reasons are all quite similar across these places. People lack time to cook their own meals, yet they are interested in trying other kinds of food and the prices are generally reasonable. However, should we stop cooking altogether?\n" +
            "The majority of people consider their lives to be too busy and cooking would not be a priority. These days most people work full-time and have many other responsibilities. Many people also have a misconception about the amount of time that is required in order to cook a simple and nutritious meal. There are a lot  dishes that can be done  with little time and with few ingredients. \n" +
            "Another benefit of cooking from scratch is that we are fully aware of what is in our food. Despite the delicious taste of these take-away meals, we hardly ever know how it is  cooked and the quality of ingredients. In order for the industry to make a profit, they will often choose the cheapest ingredients. As a result, these types of meals are often not very nutritious.\n" +
            "Lastly, we can save money by cooking our own meals. Even though the cost of ready-made meals are normally quite reasonable, still we will  always find ourselves saving money when we buy ingredients and cook at home. \n" +
            "In conclusion, it was acknowledged this  current tendency to buy convenience food which helps us through" +
            " our busy daily lives. However, it was also noted that we can largely benefit from cooking from scratch.","The trend of taking a gap year out from your current job or studies has vastly grown  since the 1990s. How come that more and more people make the leap: what jobs do they go for and what benefits do they reap? \n" +
            "Waiters or cashiers in fast-food restaurants are common jobs picked for a gap year. It is a real opportunity to gain customer-facing experience, to learn to work under pressure and of course to save money for future projects. A young and a flexible workforce appeals to employers which expect a high turnover in that sort of job. The experience can prove hard though, as working conditions including a sustained pace and regular late shifts may be poor. Eventually, the range of skills developed will certainly help you to stand out when applying for jobs in the service industry. \n" +
            "Volunteering for a charity, hospital or care home is another option for those looking for a more compassionate experience. It can be personally very rewarding as you may learn a great deal about yourself in helping others in need. If you intend to pursue a career in healthcare, it is also a real way of demonstrating your motivation when applying to school or university. The drawback is on the financial side since volunteering work is by definition not paid. \n" +
            "If a thirst for adventure is close to your heart, you might want to consider travelling. It doesn’t have to be far, we sometimes forget the travel experience can be right on your doorstep so it fits the bill for tight budgets. Going for an abroad option means an extra financial effort but you can get to know a different country, meet different people, improve your language skills and also more broadly learn how to get by in life. And most recruiters certainly appreciate candidates able to speak a foreign language. \n" +
            "All options have their pro and cons, but at  the end the best advisor is unmistakably yourself. " +
            "Ultimately, you probably won’t regret taking a gap year simply because you will not only enhance your CV but also gain maturity and many other useful life skills.\n","I have often asked myself whether it is different being a teenager nowadays than when I was that age. Are the problems still the same?\n" +
            "The years between 10 and 20 are certainly a difficult time in everybody's life because one’s personality is developing and this makes a teenager generally more vulnerable than an adult. I am convinced that when it comes to media it is demanding to deal with for young people today. Advertisements are very prominent in our modern world and teenagers normally spend a lot of hours watching television or surfing the internet, which makes them potential customers. Furthermore, many teenagers have more money to spend than maybe twenty years ago and you often hear about families taking loans for expenses like technical equipment or mobile phone bills for their children. Certainly in the current economic climate many parents face tough decisions especially when it comes to what they can afford for their offspring. The most important point is that teenagers are often an easy target for companies advertising their latest gadgets Many teenagers will buy it if theyjust manage to convince them that their product is an absolute ‘n'|ust—have', because the pressure of belonging to a certain group, feeling accepted and not being an outsider is a big issue for a young person.\n" +
            "On the other hand, teenagers are trend setters. They have to create new ideas to be unique orjust different from their own parents and this often sets the trend for a whole generation. Being special and fashionable is so important and therefore one needs to spend money on clothes, computers, games or phones to be part of your teenage generation and to find common grounds to make friends and have a fulfilling social life.\n" +
            "Personally, I find it quite shocking when reading about the psychological strategies advertising companies use to gain influence on young people to sell a product. They are also often exploiting the creative energy of teenagers and it is almost impossible to escape the world of advertisement.\n" +
            "To conclude, I believe it is not feasible to prohibit adverts for teenagers. Furthermore, parents cannot" +
            " avoid their children coming into contact with it, but it needs sensible adults helping and supporting teenagers in developing their own personality and sense of taste without the powerful influence of adverts.\n","These texts both deal with the relationship between teenagers and advertising.\n" +
            "The first one focuses on how advertisers exploit young people, taking advantage both of teenage preoccupation with the media and of their susceptibility to peer pressure combined with a wish to appear ‘cool'. The second text is less critical of the relationship between marketing and young people. It presents the young as having a very positive influence on the quality of modern adverts, helping to make them much wittier and more original than ever before. This text maintains that teenagers‘ impact on advertising derives partly from their predilection for what is intriguingly new but also, more particularly, from their own creative energy.\n" +
            "This energy has been channeled into advertising, raising it arguably to the level of an art form.\n" +
            "While l appreciate the arguments put forward in both texts, ltend to feel more in sympathy with the approach of the first one. l suspect that advertisers are quite cold—hea rtedly prepared to exploit the youth market, keen to capture the attention - and the cash — of the new generation and well aware of how young people are perhaps more easily influenced than their more cynical elders.\n" +
            "I would accept that advertising can be very creative and l personally often find an advert in a magazine or a TV commercial attractive to look at or enjoyably humorous. lt does not seem unreasonable to suggest that many people with artistic talents are attracted into the advertising profession. However, I do not see that as having any direct connection with teenagers. Those who create the most original adverts are certainly likely to be young but in their twenties or early thirties rather than their teens. Moreover the appeal of the more sophisticated advert is surelyjust as powerful for the older generation as for teenagers.\n" +
            "\n","Amusement Park\n" +
            "I have recently visited an amusement park while on holiday. lt had many exciting features including a 5-D cinema, boating lake, electronic video games and rides of all sizes ranging from simple ones For children to much larger rides for thrill—seekers. The 5—D cinema is exciting as it is a relatively new technology and unavailable near me. A documentary about sharks was showing when l visited. The 5—D experience is amazing, and when things come out at you from the screen they look very realistic. When this happens it makes people scream, like they were on a rollercoaster. There are more rides than anything else at the park as this is the reason many people go - For the exhilarating experiences The larger rides have long queues and can take up to an hour to reach the front. The one that stood out for me was ‘The Extreme Drop‘, which shoots you up a steep track at about 100kph before pausing at the top where you look down for a few seconds at the ant-like people on the ground before hurtling towards them at an even greater speed. This ride has an incredible exhilarating rush and provides the loudest screams of any of the rides. There is a second queue for this ride which takes a little longer than the main one, but you get a seat right at the Front ofthe carriage. l would recommend joining this queue for any ride available as you get the best views and biggest adrenalin rush.\n" +
            "Amusement parks make a huge contribution to the quality of life for local residents. They not only " +
            "provide entertainment for the local residents, especially for young families during school holidays, they also bring jobs and money into the area. As well asjobs within the actual park, amusement parks help increase local tourism, which can provide a vast amount ofjobs in a variety of different areas for the local residents. This will then provide a lower rate of unemployment in the area and a higher standard of living for the local residents.","Motorsport is very big in my country, and the highlight of the motorsport calendar is the Formula 1 grand-prix held here every year. Formula 1 travels the world visiting about 15-2O countries a season, each country holding one grand-prix race. The whole event takes three days to complete and always follows the same format: Friday — Practice, Saturday — Qualiﬁng, Sunday — Race. 1O teams compete with 2 cars per team in the grand-prix.\n" +
            "First, second and third place all receive a trophy at the end of the race. All three days are broadcast on TV, but the highlight is the race itself, which has the largest viewership. The TV coverage improves each year as technology gets updated quicker than ever before. Every year there are always new innotive ways to show the race. This year there were cameras mounted on cars, cameras on zip—lines above corners to create unique angles and Z2-D cameras to capture the race as its never been seen before. Each year the broadcasters also try to improve the graphics displayed on the W screens with more and more detailed ‘Heads Up Displays’ (which are similar to the HUD used in video games) of what the drivers are doing in the car, so the viewers can see where, when and how much a driver is breaking, changing gear or accelerating. Viewers can also hear conversations between drivers and their pit-crew. All of this makes the viewer feel closer to the action and like they are involved in the race.\n" +
            "As motorsport is very prominent in my country the grand-prix has been used to show off not only new " +
            "technology, but also the national pride within the country. Irrespective of whether any of the competitions are from here, we celebrate F1 as a nation, and are proud that the race is held here. This is greatly helped by TV coverage always pushing boundaries and the fact that many people in the country will be doing the same thing at the same time. lt gives you the sense of unity.\n","Dear Editor,\n" +
            "I was interested to read your recent feature on young people's participation in voluntary projects. l was impressed by the way in which the volunteers had not only provided valuable help for those less fortunate than themselves but had also gained a great deal themselves from the experience. They had blossomed as people and had often clariﬁed their own career aspirations as a result of the work they had been involved in.\n" +
            "I should like to suggest a couple of other projects that I think it would be beneficial for youngsters to volunteer on. The first is a programme for schoolchildren with learning difficulties. Cuts in funding mean that this will have to close down unless volunteers can help to run it. It has been an enormously successful programme, helping many youngsters to develop skills that will stand in good stead throughout their lives, and it would be a great pity were it forced to fold.\n" +
            "The second is an environmental project keeping the forests around our town in good order. Work there involves clearing away dead wood, planting new trees when necessary and tidying paths and picnic areas. The forest is a valuable resource for city dwellers and maintaining it in good order is of great benefit to the public as well as to the flora and fauna of the forest.\n" +
            "Taking part in these projects would teach teenagers new skills — helping children with disabilities to learn, for example, or caring for the environment. However, more importantly perhaps, doing so would expand those young people's horizons making them aware of aspects of life which were previously almost certainly little known to them. Contributing to society through such voluntary work will help youngsters to develop a sense of responsibility towards the world they live in. All of this should prove of considerable value in future years both to them as individuals and to society as a whole.\n" +
            "Yours faithfully,\n" +
            "Pedro.");
}
