import java.util.Arrays;
import java.util.List;

public class B2_Texts {
    public List get_texts(){
        return texts;
    }

    private List<String> texts= Arrays.asList("I feel you've made an error between an essay and a reaction to a piece of work. Your personal hang-ups are inconsequential to the merits of the movie. It becomes more an observation of how people reacted to the movie, more so than anything the movie embodies. You've talked less about the movie itself and more about emotional empathy connects with others. It's a welcoming emotion and message, but doesn't so much tell me much of anything about the movie.\n" +
            "The only real observation you've made in the video was the emotional outburst by the MC's mother to be " +
            "open about emotions, relating it to the message of the video. It comes off more as communicating a message more than actually examining or talking about the movie. You've done the same with 3 gatsu no lion regarding people having value. It come off as you being forced to talk about the video because other people are making videos about it. You even preference this point many times in this video, and it's a wonder how you don't think that isn't manipulation to a degree but recollecting emotions is. Is immediacy the only standard by which emotions can be conveyed more than what is said?","I want to thank you for helping lessen the disconnect between me and my emotions.  You seem to feel things in a similar way to me, and over time your videos have made me feel things more directly.  Even when you talk about issues that I don't have personally, such as gender identity, hearing the way you feel them helps me.  Recently I've actually been starting to feel things other than anger and frustration without having to look at them and decide that's what I'm feeling, and it's nice.  I'm sure I'll always be quite a dispassionate person, but it's a relief to not feel that my emotions are alien to me, or at least not as much.  There seem to be a fair number of people here complaining that you didn't talk enough about the film, but to me this was like the cherry on top.\n" +
            "Thank you for making me a more complete person.","The ending of Koe No Katachi is one of my " +
            "favorite endings for any anime movie, why is this... throughout the entire movie Shoya never cried, not once, during all of the difficulties he had to face, he was always, disconnected. Then during the end when he finally opened himself up and started crying, spurred by all of the people close to him flashing through his mind, it was so emotionally satisfying for me because I felt like he finally and truly confronted himself, and how he was feeling and just let it all go, and during that whole scene, I had tears in my eyes as well. Its such a satisfying and uplifting ending that it completely grabbed me by the heart and took me for a roller coaster ride, and it will remain as one of my favorite endings of any anime film I've ever watched. This video was actually great and made me just wanna pour out what I feel through the comment section, I love your work.","This is the reason in real life some people are not directly opening up their heart. Because most of us are afraid how other individuals will respond, act, and react. Since it is quite obvious that bullying is still a problem in today’s world.\n" +
            "I would rather be direct or takes risks like opening up my heart other than just keeping all the feelings deep within me.\n" +
            "I understand that we might not wanna open up although, I rather be action oriented because I’m a Libra sun. However, Scorpio is my ascendant and moon sign considering they are fixed.\n" +
            "In psychology, it should be pretty obvious that Scorpios are like the personification of someone else who would have a fixed mindset.\n" +
            "Also coming from the heart if not one notices is that there are two words. Hear and art which creates the word heart.\n" +
            "The art of hearing reminds me of this video, and the movie Koe no Katachi in English it means a silent voice. Considering that I’m harsh while being soft spoken, and kind are my positive traits.\n" +
            "No matter how we feel all of us are already direct or we do not show our emotions. But being honest " +
            "about your feelings, open yourself up to people who are open to other honest feelings about themselves.","I think \"microservices\" is so appealing because so many Developers love the idea of tearing down the \"old\" (written >12 months ago), \"crusty\" (using a language they don't like/isn't in vogue) and \"bloated\" (using a pattern/model they don't agree with) \"monolith\" and turning it into a swarm of microservices.\n" +
            "As an Infrastructure guy, the pattern I've seen time and time again is Developers thinking the previous generation had no idea what they were doing and they'll do it way better. They usually nail the first 80%, then hit a new edge case not well handled by their architecture/model (but was by the old system) and/or start adding swathes of new features during the rewrite.\n" +
            "In my opinion, only the extremely good developers seem to comprehend that they are almost always writing" +
            " what will be considered the \"technical debt\" of 5 years from now when paradigms shift again.","My family painted about half our house ourselves when I was about a pre-teen. My mom just hired a painter to paint her new house. The painter didn't take an appreciably shorter time period than a couple pre-teens did. IIRC, it took us about a week for about 800 square feet worth, and it took the professional 3 weeks for 2400 square feet. And yeah, we did the whole masking-tape, dropcloth, and primer routine as well, and our corners were just as good. (I was gonna say we probably took more cajoling, but given the number of times my mom had to call the painter to make sure he showed up and would have it all done by move-in, I'm not sure that's true.)\n" +
            "Painting isn't a profession with a particularly high return on experience. You hire a painter for " +
            "comparative-advantage reasons. It may take him just as long as it takes you, and several thousand " +
            "dollars more, but chances are you can make more than several thousand dollars in the time you would've spent painting your house. (If you can't, you may want to re-think hiring a professional, and instead go into business as a painter yourself...).","There is also another effect, which I call recursive over-valuation.\n" +
            "The \"high-end\" art collectors tend to be extremely wealthy, and - with of course some exceptions - wealthy people are wealthy also because they care about money.\n" +
            "So, imagine that you are a wealthy art collector and you have just paid - let's say - 100,000 US$ for a painting by an \"emerging\" artist.\n" +
            "It is only human to show off your new painting, and the people you frequent are likely to be also wealthy and art collectors.\n" +
            "So, if you have a name as an art collector, that painting soon becomes in your elite a \"set point\" for the value of the new artist work.\n" +
            "The year later, a gallerist that is selling at 115,000 US$ another similar painting of the same artists can well say \"Last year TheOtherHobbes bought a similar one for US$ 100,000, and you know him, he wouldn't pay that kind of money if it hadn't this value\".\n" +
            "And this sets a second precedent, and it goes on.\n" +
            "BTW it is all in your interest to \"defend\" and \"promote\" the artist (because you defend your investment into it) even if the painting is awful.\n" +
            "In a couple of years this way you will be able to re-sell the painting for - still say - US$ 200,000 " +
            "while having - besides the profit - reinforced your fame as good investor and educated art expert, capable to see the potentiality of the artist ahead of all others...","Professional art is a big trading card game where the cards don't have attack/defense values but attention/exclusivity.\n" +
            "Maximisation of good feelings when hung on a wall is just as valid as a \"+n attention\" modifier as scandal, backstory (this is where \"(self) expression\" has its place) or innovation. The scraps of exclusivity that can be attained from craftsmanship or materials are utterly dwarfed by exclusivity derive from the artist being dead and famous.\n" +
            "Works that are nice to look at tend to fall short in exclusivity, because design is abundant. But in the" +
            " eyes of someone who rejects the idea of \"ugly art\", exclusive reliance of nonaesthetic attention drivers is almost a form of cheating.","I got started with Stratego around age 7-8 after my dad taught me.\n" +
            "I showed my friend group and we got bored of the base game very quickly, so we started modifying it and making custom versions. We had a double-wide version (just a hand drawn grid hanging off the side and custom pieces made out of cardboard and stickytape), rivers, boulders, tanks (2x1 pieces), 1v1v1, custom scenarios, etc.\n" +
            "We eventually moved on to HeroQuest and then discovered Warhammer (but couldn't afford it so we used to play our own DIY version with LEGO and dice).\n" +
            "Those rapid prototyping and iteration skills I learned at an early age massively helped me in life and they're used daily in my role as an Infra/Ops Engineer.\n" +
            "I also have a published board game (and hopefully more to come)!","There's also something to the notion that we want our regulatory bodies and government agencies to be slightly 'conservative', to avoid waste and avoid short-term folly. Our public institutions should live for generations, and have transparency and ethical demands placed upon them by the citizenry.\n" +
            "We could collectively decide to eliminate a lot of red tape in government, no problem. It's just the " +
            "effect of unchecked, unsupervised, unaccountable governments that make us want that red tape in the first place. Todays Justification Paperwork is yesterdays front-page scandal...","The vast majority of police in the USA are not federal police, only federal government workers, not state government workers, are affected by this.\n" +
            "Essential workers, such as military, are still required to turn up to work, they just don't get paid. It's not the US Government would stop wars just because they can't pay their bills.\n" +
            "Congress, funnily enough, is actually except from the shutdown and members of congress still get paid, which is a bit perverse in my eyes.\n" +
            "As for things like electricity, I assume they just put it all on credit, it's not like the government " +
            "isn't going to pay the power companies when they finally approve the budget. I usually have a month after my power bill comes in to pay it.","I'm just stuck with this thought: I spent 6 years \"accomplishing\" very little. Others (programmers eg) will have 5 years advantage on me, or even more, as a lot of people will have been programming from an earlier age.\n" +
            "I realize I've spent too much time playing video games, hanging out with friends and so on, to realistically be able to compete with someone who has been on a track and dedicated for 5+ years.\n" +
            "So the thought of \"You only just have to start _now_\", after I've been through 20 years of education completely paralyzes me. I wouldn't want to hire me. And I can't concentrate or focus enough to actually learn programming (been trying for 4 years now), since the negative thoughts just keep returning, and I have a hard time convincing myself that I'm wrong.\n" +
            "It feels like I'm just waiting for things to get worse, and what scares me is, that this thought doesn't" +
            " even bother me anymore, because I feel that my situation is justified.","This focuses on how to study when you're in school and taking classes. But that likely only represents a small number of years in your life, while the rest will be spent outside of school! IMO, learning how to study when you're outside of school is just as important.\n" +
            "Here's two comments I wish I'd been told earlier:\n" +
            "In the context of Computer Science, many books and research papers between the 70s and 90s cover a huge amount of fundamental topics. Newer doesn't always mean better! People were just as smart 30 years years ago as they are today. Even if the context has changed, many aspects likely remain applicable.\n" +
            "Many companies publish \"white papers\" on their technology. These are (sometimes) similar to research " +
            "papers, expect that they haven't been peer reviewed. They can be a good way to acquire certain kinds of industry knowledge, but be wary of snake oil salesmen. I generally read white papers with the assumption that the source is heavily biased towards whatever perspective is most favorable to them.","Dear Pedro , \n" +
            "I was greatly surprised when I heard that you are going to work overseas for such a long time. I was greatly surprised when I heard that you are going to work overseas for such a long time. You have to know that I will miss you, but I’m glad that you would like to keep in touch with your relatives, especially your grandparents. It’s nice to hear that you ask my opinion about teaching them how to use the computer, so I tried to write down some important things, here it is. \n" +
            "As you know, electronic communication, such as e-mail or skype has advantages and disadvantages too. \n" +
            "About the advantages: if you want to tell something very important to somebody, you don’t need to go to the post office to send a letter and wait for days to get the answer, just access the Internet and that’s it. I know that there is an other option, which is a mobile phone, but what if the person switched it off? So, the Internet is fast, and you don’t have to pay so much money for it, e.g.: you can write an e-mail in an Internet caffe too. But on the other hand, it’s possible that the computer beaks down or catch a a virus, or there is no electricity in your town. \n" +
            "You can ask an important question: how these elderly people could learn the use of modern electronic devices? My answer is, that you should show them how to call people with a mobile phone (just press the green button) or write an e-mail with a computer. After it, it’s necessary to practise these two tasks before you have, to remember the method of calling a person or writing an e-mail. Of course you can write down the steps on a piece of paper, in this way they can make it without you. \n" +
            "In my opinion, teenagers use the computer usually, because with the help of the computer they can play computer games, listen to music, read an electronic book, chat with their friends and collect lots of imformation that is necessary because of a homework. I think that elderly people don’t use the computer usually, because they don’t care about it, they don’t have the skills in this modern world to use it, but there are some people of old age who want to learn how to use it. \n" +
            "Because of this, we have to teach them to use it. I think that a person can live without modern electronic devices, like our relatives in the past, but we live in a modern world and we have to keep steps with our technology, because if we not, we are going to be stupid people after a little time.\n" +
            "I hope that I could help you with my ideas, please let me hear from your grandparents after you leave. I look forward to hearing from you! \n" +
            "Best wishes, Klaudia\n","Dear Mr Williams , \n" +
            "I saw your advertisement for language courses in London and I am writing to find out more about the courses you offer . I am thinking of attending a course for two or three weeks in August . Could you please send me more information and details of prices ? \n" +
            "I would particularly like to know how many students attend the school , and how many students there are in a class . I'd also like to know what resources the school has . For example , is there a library where I can study in the evenings ? Could you tell me something about the staff ? Are they all qualified teachers ? \n" +
            "I would be interested in having more details of the social and sports \n" +
            "programme . Are the activities included in the price of the course ? Could you tell me about the cost of accommodation too ? \n" +
            "Also , can you tell me what amenities there are near the school ? For \n" +
            "example , is there a park or cinema nearby ? \n" +
            "I look forward to receiving your reply . \n" +
            "Regards ,\n" +
            "Pedro\n","Exeter has a comprehensive selection of sports and leisure facilities . These include sports centres , running tracks , indoor bowling greens , a golf course and a driving range as well as swimming pools , sports pitches and an artificial turf pitch . Tennis courts are available in many of the public  parks , and are free to use . \n" +
            "The main swimming pool in Exeter has recently been renovated and is now very attractive . A fitness centre and sauna are also available . There is an open-air swimming pool for use in the summer months . \n" +
            "The local countryside provides the perfect opportunity for horse-riding , which needs to be booked in advance . There are many lovely walks on the nearby \n" +
            "hills . Cycling in Exeter is popular both as a recreational activity and as a convenient way of getting to work or the shops .\n","I would like to share my opinion. Recently it has become more important to me…… \n" +
            "because I finally want to live a healthy long life, so I went on a diet, this was the first step, and it is not easy, but I will not give it up. \n" +
            "In my country which is Hungary there are so many dietary habits to loose weight, people find out lots of crazy diets, but the wellknown is that you should eat five times in a day, and little portions, drink two or three liter water, fruits and vegetables as much as you can, and do whatever sports from running to swimming. \n" +
            "I may say that the Hungarian dishes likely contain a lot of fat, because we eat meat with meat, rice, potato and little fruits and vegetables. Well, it is not so healthy. As far as I am concerned, I do not like the Hungarian cuisine, there are a few dishes that I like, but usually I do not eat Hungarian dishes. \n" +
            "There are other kinds of food that I can not stand which is frozen or oven-ready meals. It is not healthy at all, people buy it because they want to eat something and they do not have much time, but this is the only advantage of frozen food. I always try to have time to make some food for myself, it can be a simple sandwich or a soup.\n" +
            "There is a difficult question and it is hard to decide to cook something at home or eat something in a restaurant. I like eating in a restaurant because there is a friendly atmosphere, delicious dishes, appropriate service. But I do not have time to relax and go to an Italian restaurant (which my favourite by the way), and unfortunately, money is an important reason for me, because there are many expensive restaurants and I can not find a cheaper one in my town. So instead of eating out, I cook something at home and I imagine that I am in a famous restaurant.\n" +
            " In my opinion, diet is a good way to keep our body in a better condition, and if we choose a proper diet with sense we are able to live a happy and long life without illnesses and diseases with our loved ones. If we are lucky and successful, we can teach our friends how to do a diet and how to stay healthy.\n" +
            "I hope that with this comment I could help for many readers, all my advice is when you choose a diet, listen to your common sense!\n","Dear Sir / Madam, \n" +
            "I have your advertisement for three flats in the Grenberg area. \n" +
            "My client, Jana Wolski, is interested in renting the 100 square metre attic in the centre of the town to accommodate both herself and her university sculpture work. \n" +
            "I can see the rent is EUR 950 per month, but I would also like to know if a deposit is payable and if so how much. I assume the flat is currently vacant and that the tenant can move in immediately. \n" +
            "Jana would also like to inspect the flat. I wonder if that could be arranged for next Thursday at 10.30. I would be grateful if you could send me the exact address. \n" +
            "Jill Pipes \n" +
            "Accommodation Office \n" +
            "Grenberg University\n","The Golden Eagle pub on the Meckham Road has finally closed its doors to business after more than eighty years. \n" +
            "The last night, Saturday, saw a full house. Over two hundred people turned up for a last drink with the party mood spilling out onto the pavement. \n" +
            "The closure was confirmed by the licensing committee of Grenberg City Council last month even though a thousand-strong petition against closure had been handed in by local residents. The committee sought the closure after repeated warnings about noise had gone unheeded. \n" +
            "Reactions in the neighbourhood were understandably mixed. Long term local resident, eighty-year-old Jack Hemmingway said, “A very sad day indeed, I had my first drink in there when I was fourteen in 1946.” \n" +
            "But others welcomed the closure. Rebecca Gold, an office manager, said, “I sometimes could not get to sleep till after midnight because of the noise. I was falling asleep at work.”\n" +
            "Planning permission has been given to turn the building into three residential flats.\n","Beyond the Graves by Rudolph Duvall was the first adult play which I saw at the age of twelve. It is also one of the best plays ever written, so I was eager to see Brian Smith’s rendition which had its first performance in the Grenberg State Theatre last Friday.\n" +
            "The play features a nineteenth century family torn apart by the competing claims of modernity and tradition. Gertrude, the only daughter of the rich farming family, wants not to marry, to live in the town and to study art. The relations between Gertrude, her parents, brothers and friends are intricate and delicate.\n" +
            "I was horrified, therefore, to see Smith portray these touching and difficult matters in the form of a comedy. Even in its own terms the comedy failed as Sarah Jenner, Playing Gertrude, is no comedy actress. In the end the play fell flat; and one could feel the wave of confusion and disappointment in the auditorium. \n" +
            "A disappointment indeed! \n","“People in all countries are fundamentally the same.” \n" +
            "The core physiological and mental make up of all human beings are the same, but the values and behaviour of people are moulded by different cultural histories.\n" +
            "Many of the structures that determine human life and behaviour are not within the power of human beings to change. Our physical capacities (e.g. we can walk but not fly), our need to live in communities, and our capacity for language are fixed. Even areas like differences between men and women and the themes in literature have a fixed pattern across societies over time. \n" +
            "Yet, society and technology do mould people. The way people live and think today in the twenty-first century is different from that of the nineteenth. The role and relationship between men and women have changed, the structure of families has changed. \n" +
            "In conclusion, similarities there are, but also differences between countries, within countries and over time.\n","Dear Recruitment Administrator, \n" +
            "I have recently seen your advertisement for an office manager on the internet recruitment site ProfNow. com. I am interested in applying for the position. \n" +
            "I have enclosed my CV for your perusal, but I would like to highlight a few points. I have a relevant degree and have practical experience of managing a small company. I speak English well and have a basic command of German. \n" +
            "I live in the area and could start work immediately. \n" +
            "I would be grateful if you could consider my candidature and call me for interview at your convenience. \n" +
            "Yours faithfully, \n" +
            "Edwina Smith \n","Shoes4U is experiencing a rapid upswing in sales this year, confounding critics who claim that shoe manufacturing can no longer succeed in a high wage economy. \n" +
            "The main mass production Hart shoe factory closed in Meckham over a quarter of century ago in 1983. It simply couldn’t compete with cheap manufacture in Asian and other low wage economics. But left behind was a wealth of experience in shoe making. \n" +
            "Leo Bernard had just finished his apprenticeship in 1983 when the factory closed. Though made redundant, he started making fashion shoes in his flat and began experimenting with design. “I couldn’t make a living from handmade shoes, but I was learning fast,” says Leo.\n" +
            "He built up his business slowly and carefully. “Training and personal responsibility were the key. I chose the right people and trained them well. Everybody was on flexible contracts.”\n" +
            "And today Shoes4U employs twenty people and has a turnover in the millions. “It’s all about finding a niche and remorselessly exploiting it,” Leo insists. \n" +
            "Perhaps other entrepreneurs should follow Leo Bernard’s advice.\n","Dear Sir/Madam, \n" +
            "On Friday 22 March two of my employees, as part of their work duties, took the 897 InterRegio bus (13.06 departure) from Grenberg to Meckham. I have two serious complaints with the service. \n" +
            "First, the bus was thirty-five minutes late, apparently due to the difficulties in finding a substitute after the scheduled driver telephoned in sick. Second, in an attempt to make-up time, the driver, without any announcement to the passengers, by-passed Meckham on the motorway. My two employees had no option other than to take a taxi back to Meckham. \n" +
            "As a result of this poor service my employees were not able to attend a crucial business meeting which resulted in financial loss. \n" +
            "I request from you a formal apology, and an offer of compensation. \n" +
            "Yours sincerely, \n" +
            "Leo Bernard\n","A strong corporate culture can indeed help a firm prosper. But much will depend on the content of that culture. \n" +
            "Undoubtedly, the core to corporate success is economic not cultural. Success is a matter of having a product in the market and being able by means of the right capital outlay to minimise costs and maximise revenue. The ideas which concern the production process – or the organisation of a service – are for the most part of a technical nature. So what kind of space is left for corporate culture? \n" +
            "A corporate culture bears not on technology but on the company’s employees. An effective culture can give the employee a sense of worth and purpose, thus leading to higher levels of loyalty and productivity. It is nonetheless possible to imagine strong actually existing cultures in a company which are dysfunctional. \n" +
            "In conclusion strong corporate structures can help a firm succeed, but not necessarily so.\n","Dear Charity Committee,\n" +
            "I’d prefer to support a Charity for Leopards. Leopards are amazing and\n" +
            "beautiful animals. They can run extremely fast, are wonderful hunters and\n" +
            "manage to catch smaller animals by hiding in the trees at night. They are\n" +
            "powerful. I’d rather support leopards because they are related to animals\n" +
            "like lions and tigers and only sometimes hurt people. They can survive in\n" +
            "water and eat fish, so I think it is easy to help them.\n" +
            "I am not in favour of supporting a charity for Giant Pandas or Elephants\n" +
            "due to the fact that Giant Pandas and Elephants get a lot of publicity in\n" +
            "the world. There are many charities for Elephants and Pandas and zoos\n" +
            "look after pandas and many people go to the zoo and give money for\n" +
            "pandas. I wouldn’t support Blue Whales because they eat tons of krill and\n" +
            "this means that other ocean animals have less food.\n" +
            "With best wishes,\n" +
            "Barbara Plum\n","Dear Santiago\n" +
            "I have just heard that you want to leave the family legal business to go\n" +
            "and follow your own career.\n" +
            "As you know your family are upset with this decision as they had always\n" +
            "thought it would be you to carry on the family firm. I know the family\n" +
            "business takes up so much time. It must be tempting to go and do your\n" +
            "own thing so you can feel more independent and meet more people in a\n" +
            "larger workplace.\n" +
            "However, have you really considered the advantages of continuing the\n" +
            "family firm? It’s wonderful to be able to work with those nearest to you\n" +
            "that you can really trust. Also there is a real sense of pride and\n" +
            "satisfaction in keeping up the family reputation.\n" +
            "Did you know that 65% of all businesses are family ones but only 3% of\n" +
            "these businesses make it to a fourth generation? Just imagine how proud\n" +
            "you would be if you could pass on the business to your children!\n" +
            "I hope I can persuade you to change your mind.\n" +
            "Your friend\n" +
            "Esmeralda\n","Dear Mrs Shelton , \n" +
            "I am writing to you on behalf of the Forkdale social committee . You perhaps know that we are active in trying to build a better community in Forkdale . \n" +
            "As part of our endeavour we hold a monthly meeting at the town hall and invite all of our 32 members . During these meeting we try to limit our focus to just one major issue and this month we are trying to address the problem of there being insufficient green areas in the town . Basically , we want a greener Forkdale and that means more trees and more parks . We understand that Mr George Grant MP is particularly interested in this issue , and consequently , we would like to extend an invitation to him to join our meeting . \n" +
            "All our members feel that Mr Grant can make a valuable contribution to the meeting and as such we hope that he will be able to attend . We look forward to hearing back from you . \n" +
            "Yours sincerely \n" +
            "Tracy Emerald.\n","At the other end of the spectrum, weaker magnetic fields should in theory be overcome by gravity, initiating star formation.\n" +
            "Understanding patterns in the magnetic fields of star-forming regions might help us predict how they will evolve in future. The strength of the magnetic fields in space could also influence how massive stars grow to be, and, potentially, whether planetary systems can form around them, Dr Santos added.\n" +
            "The US-German Sofia (Stratospheric Observatory for Infrared Astronomy) observatory is based around a modified Boeing 747SP aircraft. While flying at altitudes of about 12km (41,000ft), a large door in the aft fuselage is opened, allowing a 2.5m diameter telescope to observe the sky.\n" +
            "The aircraft can rise above most of the water vapour in the Earth's atmosphere - which can block some infrared wavelengths from reaching the ground.\n" +
            "The project is managed for Nasa by the Universities Space Research Association (USRA), while the German " +
            "parts of the venture are managed by a special organization - the DSI (Deutsches SOFIA Institut).\n","Policy-makers employ a wide range of measures to tackle the problem of traffic congestion. Enforcement schemes such as setting strict speed limits on major roads and the use of congestion charges in city centres are two such examples as are vehicle exclusion zones or parking restrictions in busy pedestrian areas. However, it also makes sense to encourage motorists to become less reliant on their car. This can be achieved by making public transport more efficient and promoting the benefits of car-sharing with work colleagues, thus reducing weekly fuel bills. And the increasing number of cycle lanes on many roads is further evidence of how to win the hearts and minds of motorists in the fight against congestion.\n");
}
